### ISSUE TITLE
Refactor `Connection::transmit_handshake()` to take care of TLS writing

### ISSUE THREAD

**Issue by djc** [djc/quinn#101]
`transmit_handshake()` is currently used in a number of places that go like this:

```rust
let mut outgoing = Vec::new();
self.tls.write_tls(&mut outgoing).unwrap();
self.transmit_handshake(&outgoing);
```

We should reevaluate the API to see if `transmit_handshake()` can take the to-be-transmitted handshake bytes directly out of the `TlsSession`.

**Comment by Ralith** [comment]
Fixed by #98.
