### ISSUE TITLE
Update traffic keys automatically when reaching a AEAD safety limits 

### ISSUE THREAD

**Issue by stammw** [djc/quinn#121]
AEAD cryptographic algorithms have a limit of data volume they can transmit to the open. They can be found in [TLS-13 rfc8446 section-5.5](https://tools.ietf.org/html/rfc8446#section-5.5).

Based on these values, connections should initiate [key updates](https://tools.ietf.org/html/draft-ietf-quic-tls-16#section-6) when necessary. A configurable threshold should be checked against the amount of data transferred since last key updates to trigger it.

**Comment by Ralith** [comment]
As of draft 29, key updates must be initiated earlier if large numbers of authentication failures occur: https://quicwg.org/base-drafts/draft-ietf-quic-tls.html#name-minimum-key-update-frequenc
