### ISSUE TITLE
Coalesce outgoing packets

### ISSUE THREAD

**Issue by Ralith** [djc/quinn#142]
During handshakes, it's common for multiple small QUIC packets to be transmitted in rapid succession. These can be concatenated into a single UDP packet to reduce overhead. This could be done by deferring the actual UDP transmit until at least a full MTU of QUIC packets is available to send or no more need to be immediately sent.

Once 0-RTT support is implemented, this could further reduce overhead by allowing outgoing connections with 0-RTT data to use that data in place of the bulk of the `Initial` packet's padding.

**Comment by pop** [comment]
Good first issue you say? I'm interested in this project and want to help out. Where should I go for support and/or mentorship to work on this issue?

**Comment by Ralith** [comment]
Feel free to hit us up on [the gitter](https://gitter.im/djc/quinn)! The key to this issue will be changes in/beneath `Connection::poll_transmit`, where packets are assembled on-demand.

**Comment by Ralith** [comment]
I think this got fixed in #342.
