### ISSUE TITLE
Design API for 0-RTT and 0.5-RTT data

### ISSUE THREAD

**Issue by Ralith** [djc/quinn#148]
0-RTT data can be replayed by an attacker, and 0.5-RTT data (data sent by the server using 1-RTT keys before the client's TLS FIN is received) can be intercepted by a MITM. For some applications (e.g. fetching public data), these possibilities are harmless, and the reduction in latency versus 1-RTT is desirable. For others (e.g. performing non-idempotent operations or fetching private data), these are dangerous security vulnerabilities.

A good API should support applications like the former, while making it difficult for applications like the latter to inadvertently be insecure. The simplest solution would be to not support 0/0.5-RTT data, but hopefully we can do better. Perhaps separate feature-gated APIs?

**Comment by djc** [comment]
It looks like rustls only supports client-side 0-RTT data, using this API:

https://docs.rs/rustls/0.14.0/rustls/struct.ClientSession.html#method.early_data

In other words, it does not appear to be feature-gated -- I'm a little surprised the documentation also doesn't talk about the potential of replay attacks.

**Comment by Ralith** [comment]
That does seem out of character. Scary warnings in the documentation seem like the bare minimum measures here. The separate API at least ensures people aren't using it totally by accident, though (which the current 0.5-RTT support in Quinn fails).

**Comment by Ralith** [comment]
#198 drafts an API that allows a `Handshake` object to be converted into a `Connection` without waiting for the handshake to complete by using a function documented with the requisite warnings. I think this provides a good compromise between usability and safety-by-default.
