### ISSUE TITLE
Handling CInitial with CID that matches an existing connection

### ISSUE THREAD

**Issue by djc** [djc/quinn#150]
Currently we first match on the connection ID, and only then consider that a packet might want to start a new connection. We probably need to be smarter about this.

**Comment by Ralith** [comment]
[§7.2 Negotiating Connection IDs](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#negotiating-connection-ids)
> When an Initial packet is sent by a client which has not previously received a Retry packet from the server, it populates the Destination Connection ID field with an unpredictable value. This MUST be at least 8 bytes in length.

Is this a realistic concern?

**Comment by djc** [comment]
Ah, if the initial DCID is at least 8 bytes, perhaps not.
