### ISSUE TITLE
Switch between AES-NI and software implementation at runtime rather than at compile time

### ISSUE THREAD

**Issue by est31** [djc/quinn#196]
Currently, the aes crate switches between aesni and aes-soft using a compile time switch. But most times you want to compile a binary that runs on computers that don't have AES-NI so you won't turn on aesni at compile time. Therefore, I suggest runtime switching which can be acheived by enabling the `nocheck` feature of the aesni crate and checking manually using the `is_x86_feature_detected` macro from std.

Using a fast AES implementation is particularly important for games as here low-latency is very important.

Further reading:

* https://github.com/RustCrypto/block-ciphers/pull/22
* https://github.com/RustCrypto/block-ciphers/issues/25#issuecomment-412787052
* https://doc.rust-lang.org/stable/std/macro.is_x86_feature_detected.html

**Comment by djc** [comment]
I don't think we should invest in this, and should instead use the new primitives that *ring* has, removing our use of the RustCrypto and Orion crates.

**Comment by djc** [comment]
Unfortunately for now that will mean switching to *ring* master, to benefit from @Ralith's https://github.com/briansmith/ring/pull/757.

**Comment by Ralith** [comment]
> Using a fast AES implementation is particularly important for games as here low-latency is very important.

Is this significant compared to network latency in practice when you're not maximizing throughput? Not that we shouldn't use what hardware is available, but I'd expect we can justify waiting for a minor ring bump.

**Comment by est31** [comment]
Why does using ring's aes implementation mean that wen need to integrate @Ralith 's PR? Aren't the two orthogonal? 

Using ring from git will have major problems as multiple major versions of ring can't be used together and git vs nogit is seen as major version change iirc. You'd have to fork all crates that depend on ring and will end up in a situation similar to the one that my ring update PR was at originally.

**Comment by est31** [comment]
Ok, I agree, let's just wait for a minor ring update. It's not that important if it's *only* 5 bytes per packet.

**Comment by djc** [comment]
@briansmith took me about 20 minutes to port Quinn to *ring* header protection API, and all the functional tests passed straightaway. Seems successful in my book.
