### ISSUE TITLE
Implement version negotiation

### ISSUE THREAD

**Issue by djc** [djc/quinn#2]
This is explained in section 6.2 of the draft 11 transport spec:

https://tools.ietf.org/html/draft-ietf-quic-transport-11#section-6.2

The code processing incoming handshake packets in `ConnectionState::handle_packet()` should check that the `version` in the `Initial` packet matches what's supported per `QUIC_VERSION`. If it doesn't match, it should queue an appropriate response using `ConnectionState::build_long_packet()`  (or something similar if version negotiation has slightly different needs).

**Comment by djc** [comment]
I have started on this in a branch:

https://github.com/djc/quinn/tree/negotiate

**Comment by Ralith** [comment]
As of the quicr merge, basic version negotiation (i.e. failing connections that don't support our sole implemented version) is implemented.
