### ISSUE TITLE
Implement the unreliable datagram extension

### ISSUE THREAD

**Issue by Ralith** [djc/quinn#207]
[The unreliable datagram extension](https://datatracker.ietf.org/doc/draft-pauly-quic-datagram/?include_text=1) provides an interesting escape hatch for applications requiring unusual semantics. While streams should support everything from bulk data transfer to realtime games effectively, more niche cases like IP tunneling and VoIP might benefit from lower-level primitives. This extension is simple enough to incur little maintenance cost, and the presence of an escape hatch may reassure prospective users of QUIC's suitability to demanding applications.

The interface should consist of new functions to read/write datagrams. The stream read/write error enums should not be reused, as datagrams have different error semantics: writes may be blocked or may fail due to exceeding the MTU, and reads are infallible.

**Comment by nehri97** [comment]
Hi, I'm trying to get involved with this project. Do you have any resources to point me to learn more about the topic this issue addresses, or any advice in general?

**Comment by Ralith** [comment]
Hi, thanks for your interest! The extension is outlined in the linked draft, which references terms defined in [the core transport draft](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html). Implementing this in Quinn will involve defining the new frame type in frame.rs, handling it in `Connection::process_payload`, encoding them from a queue on the `Connection` in `Connection::populate_packet`, and adding public functions on `Connection` to read/write at the application layer. You can reach us in [the gitter](https://gitter.im/djc/quinn) to discuss further as needed.

**Comment by nehri97** [comment]
Thank you for the clarifications. I'll get to work!

**Comment by gretchenfrage** [comment]
@nehri97 have you done any work on this? This issue looks abandoned, and I'm thinking of taking a go at it.

**Comment by nehri97** [comment]
Yes please go at it

**Comment by Ralith** [comment]
How should we expose the stream of incoming datagrams at the high level? Currently, an established connection yields a `(driver, handle, incoming_streams)` tuple. Possible approaches: 

1. Yield `(driver, handle, incoming_streams, incoming_datagrams)`. This might get onerous for applications that don't want datagrams, and large tuples are unergonomic even for those that do.
2. Yield a `struct NewConnection { pub driver, pub handle, ... }`. This makes the rustdocs a bit less transparent, requiring a click-through to see what is actually being returned.
3. `Connection` could have a `recv_datagram` method, but since `Connection` is `Clone` that would require us to support multiple tasks trying to receive a datagram concurrently, which complicates the internals slightly and doesn't seem like a real use case.
4. `Connection` could have a `fn take_datagrams(&self) -> Option<impl Stream>` method which only returns `Some` the first time it's called. This strikes me as a somewhat ugly hack.

I currently lean towards 2.
