### ISSUE TITLE
xavamedia.nl:4433 certificate has expired

### ISSUE THREAD

**Issue by thejpster** [djc/quinn#23]
The host xavamedia.nl is given as an example Quinn server at https://github.com/quicwg/base-drafts/wiki/Implementations but:

```
$ cargo run --example client xavamedia.nl
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target\debug\examples\client.exe xavamedia.nl`
RESULT: Err(Tls(WebPKIError(CertExpired)))
```

**Comment by djc** [comment]
Oops -- I don't yet have a good process in place to copy new server keys to the demo environment. In any case, it's fixed now, thanks for reporting.
