### ISSUE TITLE
QPACK: make header encoding concurrency possible

### ISSUE THREAD

**Issue by stammw** [djc/quinn#230]
Change `qpack::encode`  and it's underlying functions to make it possible for simultaneous calls.

Make `DynamicTableEncoder::insert` accept a `Arc<Mutex<DynamicTableEncoder>>` rather than a mutable reference and  return a `Result<(), BlockedHeaderEncoding>` or a similar type to express the encoding is waiting on a shared resource. So polling the unblocking condition becomes possible.

**Comment by Ralith** [comment]
`DynamicTableEncoder::insert` doesn't need to be aware of any locking/refcounting strategy itself; it can just take a `&mut self` and let the caller wrap it in `Arc<Mutex<_>>` (or something else) as needed.

**Comment by stammw** [comment]
As Ralith stated, the concurrency handling actually happens at the connection level (`Arc<Mutex<ConnectionRef>>`).

Closing.
