### ISSUE TITLE
Congestion Control

### ISSUE THREAD

**Issue by bkchr** [djc/quinn#24]
Hi,
do you already have congestion control implemented?

In general, what would you say, how far is your implementation?

**Comment by djc** [comment]
It can complete the handshake and exchange data, but data transfer is not yet reliable. So as you might imagine, congestion control is definitely not there yet. I hope to get there soon. I'd be happy to consult with your employer if they want to invest in getting this working for them!

**Comment by bkchr** [comment]
Ahh okay. Yeah, maybe I will try to help you. Will need to see, what my time says.

**Comment by Ralith** [comment]
As of the quicr merge, congestion control is implemented as specified in the draft-11 recovery document.
