### ISSUE TITLE
Local endpoint

### ISSUE THREAD

**Issue by ustulation** [djc/quinn#248]
Hello, if I bind to port 0 (OS chosen random available port) I would like to know what was allocated. TCP/UDP have APIs to get the local endpoint. I'm not finding in the docs as to how to get them.

Is that missing (or if it's there somewhere then apologies, can someone point it out pls) or is that deliberately omitted for some reason ? Currently I've to either hard-code the ports or if using 0 use the UDP API to get the port back and then pass the socket to quinn - which seems very round-about.

**Comment by djc** [comment]
Which UDP API are you using? Just `local_addr()`?

**Comment by ustulation** [comment]
Yes

**Comment by djc** [comment]
It's just missing. Would you mind doing a PR to add it?

**Comment by ustulation** [comment]
[Done](https://github.com/djc/quinn/pull/249)

**Comment by djc** [comment]
Great, thank you!
