### ISSUE TITLE
Dropping the connection does not close it

### ISSUE THREAD

**Issue by ustulation** [djc/quinn#251]
I can't seem to find a `Drop` impl for [EndpointInner](https://github.com/djc/quinn/blob/0a967f66e2a603a6a7849358fa5aeae18ada9bad/quinn/src/lib.rs#L528) so the dropping the [Connection](https://github.com/djc/quinn/blob/0a967f66e2a603a6a7849358fa5aeae18ada9bad/quinn/src/lib.rs#L659) does not actually do anything like [the doc](https://docs.rs/quinn/0.2.0/quinn/struct.Connection.html) says ([in code](https://github.com/djc/quinn/blob/0a967f66e2a603a6a7849358fa5aeae18ada9bad/quinn/src/lib.rs#L654).

I don't know if that's ^^^ where the `Drop` trait should be as I haven't gone deep into the source code but the end result is:

So what happens is even after I have dropped the `Connection` obtained via listening for connections, the remote can still successfully open a stream (tested with uni-directional stream) to us and continue sending stuff which we actually get a trigger for. This is a deviation from the behaviour which I see if I call close() expliclitly in which case the remote peer gets `ConnectionAborted` error and rightly so, when it tries to open a stream for writing something to us after we have closed the connection.

**Comment by djc** [comment]
There does seem to be a `Drop` impl for `ConnectionInner`?

https://github.com/djc/quinn/blob/0a967f66e2a603a6a7849358fa5aeae18ada9bad/quinn/src/lib.rs#L799

**Comment by ustulation** [comment]
Yes that true. Then is it [this bit here](https://github.com/djc/quinn/blob/0a967f66e2a603a6a7849358fa5aeae18ada9bad/quinn/src/lib.rs#L805) that's causing the problem by not actually calling the [actual close](https://github.com/djc/quinn/blob/0a967f66e2a603a6a7849358fa5aeae18ada9bad/quinn/src/lib.rs#L809) ? I'm just hazarding a guess as I've not looked much into quinn src code and there's difference in behaviour between a drop and an explicit close() so there's something somewhere not quite right.
The other reason could be that I have clones in my code preventing the dtor to be run :P - though i don't think so but ofc always a possibility.

**Comment by Ralith** [comment]
Thanks for investigating! That particular line is probably not the issue, as the "drained" state is only entered after the connection has already been fully closed; sending another close frame wouldn't accomplish anything.

**Comment by ustulation** [comment]
I'm happy to close this now as i can see all stuff regarding and spawning from this are resolved (at-least in my tests), or the admins can close it later if they think they need to work on this more somewhere.
