### ISSUE TITLE
Relation between Connection and NewStream/RecvStream/WriteStream

### ISSUE THREAD

**Issue by ustulation** [djc/quinn#252]
Further to the [bug report here](https://github.com/djc/quinn/issues/250), I can also see that children streams spawned via `IncomingStreams` stream are left untouched by `Connection::close()`. What this means is that for e.g., a `read_to_end` on a `RecvStream` will remain potentially unresolved once the peer has managed to successfully open it and send some stuff on it and then we decide to close the connection to it. Even if we fixed the linked bug and resolve the `IncomingStreams` to completeness, all the children streams continue to exist unresolved until the peer takes some action on them. They can continue to successfully do `write_all` on them on only once they call `shutdown` etc. will they make us resolve `our read_to_end`.

To manually patch this I'm currently keeping extra state such as a `tokio::sync::watch::Sender` which broadcasts to all the children streams to resolve them via stream/future selector (`select/select2`).

 This should also be fixed in quinn ?

**Comment by Ralith** [comment]
This should be handled by `Pending::fail`, but we may have a bug where don't call that for locally-closed connections.

**Comment by ustulation** [comment]
I'm happy to close this now as i can see all stuff regarding and spawning from this are resolved (at-least in my tests), or the admins can close it later if they think they need to work on this more somewhere.
