### ISSUE TITLE
Panic in BiStream::drop

### ISSUE THREAD

**Issue by nbaksalyar** [djc/quinn#257]
Hello,

We're trying to create a simple example for testing quinn with a large number of P2P connections. Our test case is: spin up a large number of clients, exchange the connection information via a server with a known endpoint (bootstrap node), and connect to each other. So effectively for 10 nodes we have 10 x 10 = 100 connections. This test scenario works fine for us most of the time when we run it with 3-4 clients, but when we try to run it with 50 nodes, it fails all the time with the following error:

```
ERROR in communication with peer 127.0.0.1:55753: ReadError(ConnectionClosed(ConnectionClosed { reason: ConnectionClose { error_code: PROTOCOL_VIOLATION, frame_type: None, reason: b"illegal frame type in handshake" } })) - Read Error: connection closed: aborted by peer: detected an error with protocol compliance that was not covered by more specific error codes: illegal frame type in handshake.

Incoming-streams from peer 127.0.0.1:55753 closed due to: ConnectionClosed { reason: ConnectionClose { error_code: PROTOCOL_VIOLATION, frame_type: None, reason: b"illegal frame type in handshake" } } - aborted by peer: detected an error with protocol compliance that was not covered by more specific error codes: illegal frame type in handshake
```

Adding further debug & tracing information shows that the frame type that violates the protocol is `PING (0x1)`:

```
TransportError(Error { code: PROTOCOL_VIOLATION, frame: Some(PING), reason: "illegal frame type in handshake: Ping" })
```

We tried adding trace logging of packet payloads in `quinn_proto::Connection::process_early_payload` - before this line:
https://github.com/djc/quinn/blob/eade6f4d9a71ed795af463f0e0e0ad5b55efe863/quinn-proto/src/connection.rs#L1423
and it produces the following output:
```
PACKET<V4(127.0.0.1:35301)>:
header: Long { ty: Handshake, dst_cid: [142, 169, 236, 244, 67, 183, 248, 234], src_cid: [65, 66, 234, 19, 73, 50, 45, 33], number: U8(2) }
payload size: 9
payload: [1, 3, 1, 0, 0, 0, 15, 0, 0]
ILLEGAL_PACKET<V4(127.0.0.1:35301)>
```

comparing to this output for a successful connection:

```
PACKET<V4(127.0.0.1:39513)>:
header: Long { ty: Handshake, dst_cid: [225, 2, 89, 206, 21, 225, 97, 231], src_cid: [156, 170, 88, 23, 69, 217, 162, 212], number: U8(3) }
payload size: 8
payload: [3, 2, 0, 0, 2, 15, 0, 0]
```
Judging from the payload size and contents, the extraneous `0x01` byte is inserted in the beginning of a payload and it translates into `Frame::Ping`.

While we're still working on a minimal reproducible example which would use `quinn` without our wrapper library, the example code we're running can be found [in this repository](https://github.com/povilasb/using-quinn/blob/8b1001e52697e4662c085fcaa09a262d5bcf9577/examples/test.rs).

Our further research uncovered that slight delays (caused e.g. by [serialisation of a large message](https://github.com/povilasb/using-quinn/blob/8b1001e52697e4662c085fcaa09a262d5bcf9577/src/communicate.rs#L84)) before writing data to the connection stream might introduce this error. Adding artificial delays with `thread::sleep(...)` also confirms that it is a timing-related bug. So far we've tried to fix it by moving the serialisation code to a separate thread, and it works with a smaller number of connections (20-30). But once we start to add more connections, they introduce a natural delay, causing the same `illegal frame type` errors again.

Moreover, occasionally a client program panics with `invalid key`, originating in the `slab` crate, being called from here:
https://github.com/djc/quinn/blob/eade6f4d9a71ed795af463f0e0e0ad5b55efe863/quinn-proto/src/endpoint.rs#L752-L753
This is probably a related error, but it might be as well something else -- we'll need a reproducible example to find out. The full stack trace for that panic [can be found here](https://gist.github.com/nbaksalyar/d07dce639afa1c2a4b5e081ee169572a).

Do you have any ideas or pointers about what happens here?

Thank you!

**Comment by Ralith** [comment]
Thank you for this very detailed report, and for the larger-scale testing! This is really great stuff.

 The illegal ping must be resulting from an error in this condition:
https://github.com/djc/quinn/blob/eade6f4d9a71ed795af463f0e0e0ad5b55efe863/quinn-proto/src/connection.rs#L2294-L2297
There's one obvious bug there: instead of (just) checking `!self.state.is_handshake()`, it should be checking that the specific packet we're actually sending is a 1-RTT packet, i.e. a packet in `SpaceId::Data` that is not 0-RTT. I'll bang out a patch for that tonight, if nobody beats me to it.

It is somewhat surprising to see `probe` and `ack_only` both being set while handshake packets are still being sent. It looks like the only other frame is indeed an ACK, so if you're receiving this packet on the client, `ack_only` would make sense as part of the server's second handshake flight, which suggests in turn that a probe timeout occurred on the server, which is unusual but possible if latencies/processing delays are high enough.

> Moreover, occasionally a client program panics with invalid key, originating in the slab crate, being called from here:

This is almost certainly an unrelated bug. It suggests an issue in state synchronization between the proto and tokio layers; the connection is being forgotten by the protocol layer before all tokio layer handles have been dropped. I suspect we're not properly preserving the proto state after an explicit close by the application. We have large changes to the tokio layer pending in #255; we'll try to get that in and stabilized soon and see if that moots the issue. If it's urgent, I can try to put together a hotfix branch.

**Comment by dirvine** [comment]
Thank you for the work here, it's amazing to have such great responses. If possible a hotfix branch would be really helpful as we are pushing the crate a bit here in testing and hope to prove it error free if at all possible. We will do some even larger scale testing as soon as we are past this part and hopefully get some further testing with more features as well. 

Thanks again, the support is superb.

**Comment by ustulation** [comment]
This hasn't fixed it but in a [backtrace has this line](https://gist.github.com/nbaksalyar/d07dce639afa1c2a4b5e081ee169572a#file-stack-trace-L24) which makes it seems that there was a BiStream involved somewhere however in our code we only ever open a uni-stream to a peer. Not sure if that helps locate the bug but mentioning just in case.

**Comment by Ralith** [comment]
> This hasn't fixed it

Strange; it definitely fixed *a* bug that would cause exactly that effect. Can you share trace-level logs for the involved connection?

> it seems that there was a BiStream involved somewhere however in our code we only ever open a uni-stream to a peer

That's expected due to implementation details.

**Comment by nbaksalyar** [comment]
@povilasb has produced a minimal self-contained example which consistently reproduce the 'protocol violation' bug when compiled in the debug mode: https://github.com/povilasb/quinn-tests. It fails both with (`master`) and without (commit `cada5cc`) the patch. The output trace log is here: [trace.tar.gz](https://github.com/djc/quinn/files/3009239/trace.tar.gz).

> Strange; it definitely fixed a bug that would cause exactly that panic

If you run the same example in the release mode, you'll be able to see this panic (but strangely enough not the 'protocol violation' error), which now shows the following stack trace:
```
thread 'main' panicked at 'invalid key', /home/maidsafe/.cargo/registry/src/github.com-1ecc6299db9ec823/slab-0.4.2/src/lib.rs:798:18
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
...
   5: std::panicking::begin_panic
   6: quinn_proto::endpoint::Endpoint::timeout
   7: <quinn::Driver as futures::future::Future>::poll
...
  17: tokio::runtime::current_thread::runtime::Runtime::block_on
  18: quinn_tests::main
  19: std::rt::lang_start::{{closure}}
```
([full bt can be found here](https://gist.github.com/nbaksalyar/2986d15c227deccad250722d863f4f7f))

Please let me know if you need more data.

Thanks!

**Comment by Ralith** [comment]
Thanks, that repro was perfect! Looks like your log sink isn't quite keeping up with the massive verbosity of trace logging, but working with the live repro was easier anyway. With #261 the test case appears to run to completion, as much as something that waits indefinitely on an empty future can.

**Comment by povilasb** [comment]
Hmm, I'm still seeing some weird results with the [quinn-tests](https://github.com/povilasb/quinn-tests) example :/
When I run the example with 20 nodes configured which results in 400 (20 x 20) connections, it seems like none of the messages passes through. `top` shows that the example binary consumes 100% CPU, but not a single 1 MB message is exchanged via any of the connections. 

I've been running the example code for the past 15 minutes or so, so it should be enough to encrypt and transfer 400 MB of data. Then this seems like an infinite loop or smth. I'll try to investigate it.

**Comment by povilasb** [comment]
Seems like it's stuck in an endless loop of sending messages. When I `strace` the example I get a continues stream of `sendmsg`:
```
sendmsg(17, {msg_name={sa_family=AF_INET, sin_port=htons(34687), sin_addr=inet_addr("127.0.0.1")}, msg_namelen=16, msg_iov=[{iov_base="\346\377\0\0\22U\363\33Gp\261\311\324l\234\226\367\333&\223-\214BL\341\v\346\4\215i\244\202"..., iov_len=612}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_IP, cmsg_type=IP_TOS, cmsg_data=[0x2]}], msg_controllen=24, msg_flags=0}, 0) = 612
sendmsg(17, {msg_name={sa_family=AF_INET, sin_port=htons(34687), sin_addr=inet_addr("127.0.0.1")}, msg_namelen=16, msg_iov=[{iov_base="\347\377\0\0\22U\340?\264!B\22\247}\313\274\243&\7\265\232\1BL\211\204)0\25\365\365\224"..., iov_len=612}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_IP, cmsg_type=IP_TOS, cmsg_data=[0x2]}], msg_controllen=24, msg_flags=0}, 0) = 612
sendmsg(17, {msg_name={sa_family=AF_INET, sin_port=htons(34687), sin_addr=inet_addr("127.0.0.1")}, msg_namelen=16, msg_iov=[{iov_base="\347\377\0\0\22U\363\33Gp\261\311\324l\234\226\367\333&\223-\214BL\32\224\240\376\21\207\377\364"..., iov_len=612}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_IP, cmsg_type=IP_TOS, cmsg_data=[0x2]}], msg_controllen=24, msg_flags=0}, 0) = 612
sendmsg(17, {msg_name={sa_family=AF_INET, sin_port=htons(34687), sin_addr=inet_addr("127.0.0.1")}, msg_namelen=16, msg_iov=[{iov_base="\342\377\0\0\22U\340?\264!B\22\247}\313\274\243&\7\265\232\1BL\262\2\354\346\\BQL"..., iov_len=612}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_IP, cmsg_type=IP_TOS, cmsg_data=[0x2]}], msg_controllen=24, msg_flags=0}, 0) = 612
sendmsg(17, {msg_name={sa_family=AF_INET, sin_port=htons(34687), sin_addr=inet_addr("127.0.0.1")}, msg_namelen=16, msg_iov=[{iov_base="\341\377\0\0\22U\363\33Gp\261\311\324l\234\226\367\333&\223-\214BL\24\216'$\357\36c\352"..., iov_len=612}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_IP, cmsg_type=IP_TOS, cmsg_data=[0x2]}], msg_controllen=24, msg_flags=0}, 0) = 612
```
Weird thing is that `recv` is never called.

**Comment by Ralith** [comment]
`strace -e recvmsg` shows calls to me, and trace logging reports activity in both directions. Have you tried a release build? I think you may just be seeing that debug mode is quite slow, particularly when handling hundreds of connections on a single thread.

**Comment by Ralith** [comment]
On closer examination, the debug does seem to not be making progress under master. However, #260 gets the debug build running (slowly).
