### ISSUE TITLE
Improve worst-case Assembler memory use

### ISSUE THREAD

**Issue by Ralith** [djc/quinn#275]
To avoid high memory use in the face of a badly-behaved peer, the stream assembler should de-duplicate stream data on receipt (as opposed to on read). Additionally, to prevent memory amplification, packet memory should not be kept alive by `Bytes` from stream frames that represent only a small portion of the packet.

**Comment by djc** [comment]
How different is this from #60?

**Comment by Ralith** [comment]
Good question. Closing as duplicate.
