### ISSUE TITLE
Random panics once connection is explicitly closed

### ISSUE THREAD

**Issue by ustulation** [djc/quinn#277]
(Hoisting it as a separate issue from where it was raised for the first time here https://github.com/djc/quinn/issues/250#issuecomment-478572701)

While testing i now see random panics from quinn when i explicit call close(). I cannot produce these in debug so my backtrace is probably useless but here's the relevant section:
```
 8: core::result::unwrap_failed
  9: <quinn::endpoint::Driver as futures::future::Future>::poll
 10: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
```
The panic is on some send-error:
```panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")'```

Currently I don't have more context as it seems to happen in some iterations.

**Comment by Ralith** [comment]
That backtrace was actually quite helpful! I think this is happening inside `drive_transmit` or `forward_endpoint_events` if the `EndpointDriver` and all `Endpoint` handles are dropped while the `ConnectionDriver` is still running, which is something we should handle gracefully. Should be a trivial fix.
