### ISSUE TITLE
Closing connection on one end does not complete connection driver on the other

### ISSUE THREAD

**Issue by povilasb** [djc/quinn#287]
Tested version: `f6c1ef0786af521e6238bff62a190657889a3993`

I have this relatively simple test: https://github.com/povilasb/quinn/blob/dropping-connections/quinn/tests/connection.rs#L7 which

1. creates connection listener
2. connects client to it
3. explicitly closes connection on the listener side

Then I expect connection drivers on both ends to get closed, but I can only witness listener connection driver being finished:
```
[server] incoming connection
[client] connected
[client] read_to_end() failed: connection closed: closed by peer:  (code 0)
[client] stream is done
[server] conn driver is done
```

I would also expect `[client] conn driver is done`, but seems like client connection driver is hanging indefinitely.

Note that the test case I provided is not complete yet but it works well for tinkering with the code. If this is indeed a bug, I'll make a PR with a proper test case.

**Comment by ustulation** [comment]
hmm we were probably reporting issue at the same time as i too created a similar one https://github.com/djc/quinn/issues/288

But it seems we are saying opposite things. For me the disconnector's driver does not resolve while the peer is totally resolve. Your title says the opposite to that but your example seems to agree with my observation

If your client closed the connection then the drive on the "other end" (server) is done in your example. You seem to have confused the observation ? (Or I'm misinterpreting the result and am confused myself)

**Comment by ustulation** [comment]
Nah ignore ^^^ you are saying the server does the explicit close and gets it's connection driver resolved. OK in that case it is opposite to what i'm observing. Well then two issues it is :)

**Comment by ustulation** [comment]
I have closed mine https://github.com/djc/quinn/issues/288#issuecomment-479518263 with the reasoning. I'm suspecting you did the opposite of what i did lol. You logged only the graceful path (the `and_then()`) and not the error path: (`map_err()`) https://github.com/povilasb/quinn/blob/b8319f5937135bded1b13d3fe9851c8628b8bb8b/quinn/tests/connection.rs#L48

So one end (which closes) gets a graceful exit while the other end gets an error exit. I was printing only the error path so was getting to my wrong conclusion. You are only printing the graceful path and probably reaching the similar wrong conclusion. Just my guess.

**Comment by Ralith** [comment]
I concur with @ustulation; it looks like you're only logging that message on success, whereas the peer closing the connections is reported as an error. You can use `Future::then` to run code whether or not a connection succeeds. You might also want to use [`Runtime::run`](https://docs.rs/tokio/0.1.18/tokio/runtime/current_thread/struct.Runtime.html#method.run) to block only until all futures have completed, which will give you concrete feedback as to whether anything has hung.

**Comment by povilasb** [comment]
:palm_face: you're right guys, sorry for false positive!
