### ISSUE TITLE
Consumption of self in Connection::close()

### ISSUE THREAD

**Issue by ustulation** [djc/quinn#289]
Hoisting this out from https://github.com/djc/quinn/issues/288#issuecomment-479502301:

Was it necessary to consume self in `Connection::close()` ? I now have to do `conn.clone().close()` in code now if it's a part of bigger object where i want to run closures in dtor (since i cannot move stuff out in dtors and `close()` consumes `self`). I mean it's clone-able and all clones refer to the same underlying connection so other clones can still call clone and panic and the semantics don't really save anyone from anything - just make it unergonomic to work with.

See std's `TcpStream` for instance. That too has `try_clone()` giving a reference to the same underlying stream and they don't really consume `self` in say `shutdown`. You can still call further shutdowns on the same handle or the clones and you will get error or otherwise depending on the platform. For us we can always return error in case of quinn since the behaviour is not platform dependent. Or you could panic (which i think what the document says) though i would usually prefer a result but am OK with whatever is decided.

However to me it appears to make it a bit unergonomic (and also different in design than what ppl might be used to coming from a std socket API

**Comment by djc** [comment]
I talked @Ralith into it, but I guess I was wrong. I'd be okay reverting it.

**Comment by Ralith** [comment]
I suspected this sort of ergonomic issue would arise, yeah; I'm on board with rolling it back.

**Comment by ustulation** [comment]
Cheers would you also be up for not panic'ing https://github.com/djc/quinn/blob/f6c1ef0786af521e6238bff62a190657889a3993/quinn/src/connection.rs#L181

and returning error instead to make sure that a bit of defensive coding (i.e., calling close multiple times if they had several clones of the connection - i'm personally not doing this but just from a user p.o.v) from the consumers don't result in a panic but an error they can choose to ignore (or panic on) if they wanted ?

**Comment by Ralith** [comment]
That comment's actually out of date; we removed it for the reasons you describe, and redundant closes are now silently ignored. Will update the comment.

**Comment by Ralith** [comment]
Fixed by #295.
