### ISSUE TITLE
0.3 release planning

### ISSUE THREAD

**Issue by djc** [djc/quinn#302]
- [x] Ownership refactor
- [x] rustls release bump
- [x] MaidSafe issues
- [x] Close behavior (anything left here?)
- [x] Backport 0-RTT API
- [x] Separate send/release types (as on nightly)
- [ ] Merge #246 (More examples)
- [x] Merge #284 (More tests)

Am I forgetting anything? Not sure how much work that last item is, depending on that it should maybe be aspirational.

**Comment by ustulation** [comment]
Hey guys would you be up for an interim publish ? Will allow us to do our first publish of using quinn (Cargo doesn't let publishing with GH deps - or at-least i'm ignorant if there's a way besides inlining the entire dep repo)

**Comment by djc** [comment]
I think we could probably do that. Do you have a particular timeline you're aiming for?

**Comment by ustulation** [comment]
lol - today :P if possible

Na it's just that we send out dev-updates to our community and would be great if they can use a cargo-published version.

**Comment by djc** [comment]
I think we'd probably still want to get in the separate send/release types (which should be easy enough), but ideally getting in the 0-RTT API too would prevent having more API churn. The former should be pretty quick, not sure how hard the latter would be.

**Comment by Ralith** [comment]
> Not sure how much work that last item is, depending on that it should maybe be aspirational.

It's a separate crate we haven't released yet, so I don't think it needs to block

**Comment by stammw** [comment]
I'm starting to address the QPACK / H3 draft updates. 

Although the current H3 related code is not really usable as higher layer features will still be missing (Frame iterator, connection state machine, settings...).

**Comment by Ralith** [comment]
I don't think #246 should block; people reviewing examples will generally be looking at git master by default, and there's an unresolved change requested.

**Comment by djc** [comment]
Well, we probably don't want to release before Monday morning PST anyway for marketing reasons, so there's still time, but I agree we can ship without it.

**Comment by Ralith** [comment]
#312 fixes interop, so merging it should block.

**Comment by djc** [comment]
Needs some workaround for #245, merging #310 and drafting some release notes.

**Comment by djc** [comment]
Release notes draft: https://github.com/djc/quinn/releases/edit/untagged-8251b477a0c396398b3d. Feedback very welcome!

**Comment by djc** [comment]
Released.
