### ISSUE TITLE
Replace ArrayVec in ConnectionId with a simple array

### ISSUE THREAD

**Issue by djc** [djc/quinn#31]
This is what I had originally in quinn. This would get rid of the extra dependency, and it would let `ConnectionId` implement `Copy`, which would obviate the need for cloning.

**Comment by Ralith** [comment]
A length field *is* needed, whether we use `ArrayVec`'s or reimplement a small portion of it. Not having `Copy` is annoying but merely cosmetic, although for a public type the effort may be justified.

**Comment by djc** [comment]
I had [an implementation](https://github.com/djc/quinn/blob/pre-quicr-quinn/src/types.rs#L6) that seemed just about as simple. I found the lack of `Copy` a little jarring in places since it seems like something that intuitively should be `Copy`, but I think having one less dependency is also a good incentive to get rid of the `ArrayVec`.

**Comment by twilco** [comment]
I'm going to take a stab at this one!

**Comment by djc** [comment]
@twilco, great, thanks!
