### ISSUE TITLE
Restrict the quinn-proto API

### ISSUE THREAD

**Issue by djc** [djc/quinn#314]
In #310, while documenting the quinn-proto API, it came up that we would like to hide more API surface from the quinn-proto. Let's discuss a little bit how/what we can do here.

The good news is that we will be able to iterate on the quinn-proto API but that we could probably keep the quinn API stable while doing so.

**Comment by stammw** [comment]
I don't know how much my concern is connected to this subject, but I figured out I needed to access (read) the `StreamId` inner value  for the `h3` implementation.

**Comment by djc** [comment]
Can you submit a PR that makes it `#[doc(hidden)] pub`?

**Comment by Ralith** [comment]
I think we could make `Timer` opaque, which is desirable as timers may be added/removed in the future. Perhaps we could take it a step further and export a `TimerTable<T>` struct that helps hide the number of timers.

**Comment by djc** [comment]
I think there's nothing left to do here for now.
