### ISSUE TITLE
Consider replacing std::sync::Mutex with parking_lot::Mutex

### ISSUE THREAD

**Issue by imp** [djc/quinn#337]
`Mutex` implementation in `parking_lot` is considered better than that of the `std::sync` and doesn't require `unwrap()`-ing `lock()` results. Other than that it is a drop-in replacement.
So the number of calls to `unwrap()` can be reduced.

**Comment by djc** [comment]
parking_lot is coming to std in 1.36, so we can just wait and get it for free.

**Comment by imp** [comment]
Well, not exactly. The `std::sync::Mutex` API is not going to change. Rather the underlying implementation will be based on `parking_lot` instead. So it will still require calling `unwrap()`.

Up to you though.

**Comment by djc** [comment]
Not sure what my position on poisoning is. It seems sensible that a Connection thread should not continue if the ConnectionDriver panicked.

**Comment by imp** [comment]
> ... It seems sensible that a Connection thread should not continue if the ConnectionDriver panicked.

Well, I am definetly not qualified enough to judge on that.
I do, in general, try to avoid calling `unwrap()` in the library code, but rather handle the situation or flag the error and let the consumer decide what to do (panic for example).
So, that's the real reason behind this.

If panicing is considered a normal thing for this project than the change suggested in this issue is indeed not productive.

**Comment by Ralith** [comment]
Quinn should never panic under sane circumstances, but if a lock is poisoned, that means we *already* panicked while the lock was held (i.e. internally) so it's a bit late to avoid that. Similarly, we rely on array indexing even though that can panic, because we should never be passing in an invalid index to begin with.

**Comment by imp** [comment]
IMHO that's a risky assertion. However, you guys are driving this project, so you get to decide. If that'd be my call I'd set

```rust
#[deny(clippy::option_unwrap_used)]
#[deny(clippy::result_unwrap_used)]
```

first thing before even starting to code. This project is a very important piece of software.

**Comment by djc** [comment]
FWIW, your comment reads as rather passive aggressive to me.

There are many potential sources of panic even just in `std` other than these `unwrap()` methods. Prohibiting `unwrap()` on `Option` and `Result` seems neither necessary nor sufficient to get to a functional library that doesn't panic in use. I would like to eventually get to a point where we have audited all uses of `unwrap()` for safety and document that, plus a comprehensive test suite.

**Comment by imp** [comment]
> FWIW, your comment reads as rather passive aggressive to me.

Sorry about that. That definetly was not intended.
