### ISSUE TITLE
Use SHA instead of Blake2 for MACs?

### ISSUE THREAD

**Issue by djc** [djc/quinn#34]
*ring* currently [does not implement Blake2](https://github.com/briansmith/ring/issues/169), so we have to pull in an extra dependency for this. @Ralith what was your original reason for selecting Blake2 for this? If it's good enough we might ask for an update in the original *ring* issue.

**Comment by Ralith** [comment]
Blake2b was selected as a convenient high-performance modern cryptographic hash function. It's fine to swap it out with another HMAC scheme (it's not even a breaking change) if you think increasing our use of *ring* is worth it.

**Comment by djc** [comment]
I'd actually also have picked Blake2b if all other things were equal. But having one less dependency means less maintenance (and less compile time), and I don't think this particular area of the code is in a particularly hot loop that the difference between Blake2b and HMAC-SHA256 will be noticeable?

**Comment by Ralith** [comment]
Yeah, should be fine. It's ran on small amounts of data for every packet that was successfully parsed but not associated with a connection, and (formerly) for every handshake when using stateless retries. No real hot loop.

**Comment by kylegalloway** [comment]
I would like to take a look at this issue. What crate does the HMAC-SHA256 algorithm come from?

**Comment by Ralith** [comment]
@djc is correct; in particular, the `reset` member of `ListenKeys` should be replaced with a `SigningKey`. Let's use SHA-512/256 rather than SHA-256 for the hash algorithm to take better advantage of current hardware, too.

**Comment by djc** [comment]
@kylegalloway are you still interested in working on this? If not, someone else might want to take a swing.

**Comment by kylegalloway** [comment]
@djc  I have gotten really busy recently. Thanks for the opportunity, but if someone else wants to take a swing, please let them.

**Comment by djc** [comment]
@kylegalloway no problem, thanks for the quick response.

**Comment by stammw** [comment]
I'd like to work on this one.

**Comment by djc** [comment]
Great! Let me know if you have any questions.

**Comment by stammw** [comment]
SHA512/256 hash seem to have a size of 32 bytes, but the `RESET_TOKEN_SIZE` is 16, the same as `stateless_reset_token` field of tls's `TransportParameters`.  Should the digest be truncated?

**Comment by stammw** [comment]
OK, so I found in the [ietf draft](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#reset-token) that it is the expected behavior:

> The output of this function is truncated to 16 bytes to produce the Stateless Reset Token for that connection.

**Comment by djc** [comment]
This is done, thanks again to @stammw.
