### ISSUE TITLE
H3: Control stream implementation

### ISSUE THREAD

**Issue by stammw** [djc/quinn#358]
Handle control streams in `quinn-h3::proto::Connection` and drive it from `quinn-h3::ConnectionDrive`, conforming to [6.2.1. Control Streams](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#rfc.section.6.2.1).

**Comment by djc** [comment]
What do you mean by handling them "in" `proto::Connection`?

**Comment by stammw** [comment]
Make the data exchanged on this stream impact the connection state, and the other way around. When some of it's state changes the connection needs to transmit some frames to it's peer. This mechanism is a part of the request life-cycle. [This table](https://quicwg.org/base-drafts/draft-ietf-quic-http.html#http-framing-layer) can help to understand what it is all about.

**Comment by djc** [comment]
Okay, but I'm confused about the part where this HTTP-level contract has to become a part of the `quinn-proto::Connection` or the `quinn::ConnectionDriver`, both of which should know ~nothing about HTTP.

**Comment by stammw** [comment]
Maybe it is a design flaw then? `proto::Connection` is the place where all the state common to requests, responses is stored.

For example: If a peer triggers a `GoAway`, receiving `proto::Connection` will set a flag. If a subsequent Request asks for a new request stream, `Connection` will lock `proto::Connection`, check the flag, return an error because it is set.

**Comment by stammw** [comment]
Forgot to mention: `ConnectionDriver` polls the `QUIC` stream that is used as control stream. It gets a `GoAway` frame. Then it locks `ConnectionRef` to set the `gone_away` flag in `proto::Connection`.

**Comment by djc** [comment]
Ah, you're talking about `quinn-h3::proto::Connection` whereas I was talking about `quinn-proto::Connection`.

**Comment by stammw** [comment]
I edited the description...
