### ISSUE TITLE
Implement QPACK encoding/decoding

### ISSUE THREAD

**Issue by djc** [djc/quinn#4]
The spec is here:

https://tools.ietf.org/html/draft-ietf-quic-qpack-00

There really isn't any code around this yet, so at first this could just be a stand-alone implementation with unit test coverage to make sure it can round-trip properly.

**Comment by evolix1** [comment]
I'm on it !

**Comment by djc** [comment]
@evolix1 hey, how are you? We're getting to the point where we want to complete the QPACK implementation. Are you interested in finishing this soon? Otherwise someone else may want to pick it up.

**Comment by stammw** [comment]
Closing in favor of #136
