### ISSUE TITLE
Futures 0.3 and tokio 0.2

### ISSUE THREAD

**Issue by jnicholls** [djc/quinn#432]
Noting that #132 is sufficient for supporting `std::future` and futures 0.3, it would be great to see a branch that moves to `std::future` and futures 0.3 officially as an alpha release. Additionally, a move to tokio 0.2 alpha to tie it all together. I'd consider this issue just a placeholder for an inevitable upgrade.

**Comment by djc** [comment]
See https://github.com/djc/quinn/pull/372. We plan to merge this to master soon.

**Comment by Ralith** [comment]
Now merged to master!
