### ISSUE TITLE
Explicitly indicate to client applications when 0-RTT is accepted

### ISSUE THREAD

**Issue by Ralith** [djc/quinn#436]
[Required Operations on Connections](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#required-operations-on-connections):
> When implementing the client role, applications need to be able to:
> - be informed when 0-RTT has been accepted or rejected by a server.

**Comment by Ralith** [comment]
Perhaps `Connecting::into_0rtt` should return a oneshot future alongside the `NewConnection`?

**Comment by djc** [comment]
That sounds like a sensible design.
