### ISSUE TITLE
Consider making the config structs opaque

### ISSUE THREAD

**Issue by Ralith** [djc/quinn#444]
Presently, quinn is configured through a handful of structs with public members. This is simple to work with, but presents a forwards-compatibility hazard, because the representation of parameters cannot be changed without making a breaking change to the interface. For example, we might want to switch all time intervals to use `Duration`. Per-field validation is also awkward to perform.

Instead, each struct could have entirely private fields and a number of setters, which could consume diverse types and even return `Result` where appropriate. If changes are made, old setters could be deprecated rather than removed wholesale.

**Comment by djc** [comment]
Sounds good to me!

**Comment by TimonPost** [comment]
Maybe something I can start with. First a list with all structs that have public fields:

_quinn_
- [ ] NewConnection
- [ ] ConnectionDriver

_quinn_h3_
- [ ]  InsertWithoutNameRef
- [ ] Duplicate
- [ ] DynamicTableSizeUpdate
- [ ] InsertCountIncrement
- [ ] HeaderAck
- [ ] StreamCancel
- [ ] HeaderField
- [ ] StreamType

_quinn proto_

- [ ] Error
- [ ] Streams
- [ ]  PacketSpace
SentPacket
Retransmits
CryptoSpace
TransportConfig
EndpointConfig
ClientConfig
EndpointEvent
ConnectionId
IssuedCid
Packet
StreamId
Transmit
ConnectionHandle
TlsSession

**Comment by Ralith** [comment]
That would be great! To clarify, this issue refers specifically to the configuration structs, i.e. `EndpointConfig`, `ClientConfig`, `ServerConfig`, and `TransportConfig`. The error enums and `NewConnection` are intended to have public contents, `ConnectionDriver` is only `pub(crate)`, and most of the other structs aren't exported from the crate at all, so field visibility is not a major concern.

**Comment by TimonPost** [comment]
Ah okay, that saves a ton of work. Thanks for the clarification!

**Comment by TimonPost** [comment]
Why don't we make those types  `pub(crate)` just for clearance?

**Comment by Ralith** [comment]
Nobody's seen a need before, I suppose. I'm not necessarily opposed to it.

**Comment by TimonPost** [comment]
Fixed `ServerConfig`, `EndpointConfig` in #482
