### ISSUE TITLE
Return ownership of messages on network error

### ISSUE THREAD

**Issue by jean-airoldie** [djc/quinn#454]
Could quinn return the ownership of the queued outgoing messages to the user in the event of a connection / transport error? This would allow users to recover from network errors without losing messages.

**Comment by Ralith** [comment]
Can you elaborate on the use case here? If an error is recoverable (e.g. packet loss), data will be automatically retransmitted where applicable. If the connection is lost with data in-flight, the portion of that data which the peer hasn't received is indeterminate.

Additionally, Quinn is designed not to buffer data for significant periods of time. If data was accepted by the transport (e.g. `SendStream::write` completed) then it should be considered sent, although you cannot rely on it having been delivered until `SendStream::finish` completes.

**Comment by jean-airoldie** [comment]
I'm talking fatal network errors, where the connection is aborted (hardware / network failure, error in the underlying transport, etc.). I would like to be able to get ownership of the data that was not received by the remote (e.g. messages that were not ACKed by the peer, assuming QUIC uses positive acks) before the connection crashed.

For instance, the `SCTP` transport implements [something of the sort](https://tools.ietf.org/html/rfc6458#section-6.1.1). Although I'm not using SCTP for performance reasons.

My use case would be a self healing servers that would resume the transmission at the last sent message. Currently, with TCP I have to implement application level ACKs just to prevent such message loss.

**Comment by jean-airoldie** [comment]
> If the connection is lost with data in-flight, the portion of that data which the peer hasn't received is indeterminate.

Can't we deduce the range of messages were loss based on the last time the peer sent a ACK? If we could, 2 clients could then deduce what was the last transmitted message and carry on with the transmission.

**Comment by Ralith** [comment]
> For instance, the SCTP transport implements something of the sort.

I don't see anything in that section discussing return of buffered application data. Can you be more specific?

> My use case would be a self healing servers that would resume the transmission at the last sent message.

Would this be adequately served by keeping track of what application-level messages you haven't yet successfully `finish`ed at the application layer? Note also that "message" is not a QUIC concept; I'm assuming you're talking about smallish single-use streams, but there are other ways to encode messaging in QUIC and perhaps that's not the one you had in mind.

> Can't we deduce the range of messages were loss based on the last time the peer sent a ACK?

An ACK confirms receipt, but it does not strongly confirm loss, especially not of data that was sent after the most recent packet referenced in the ACK. The receiver could, on reconnect, transmit an accurate record of what it received on the prior connection, but unless your messages are very large or difficult to make idempotent it would likely be faster to conservatively retransmit them without waiting for that.

**Comment by jean-airoldie** [comment]
> I don't see anything in that section discussing return of buffered application data. Can you be more specific?

Sorry, I truncated the link: [here it is](https://tools.ietf.org/html/rfc6458#section-6.1.11). Basically packets that cannot be routed are returned to the user using a `SCTP_SEND_FAILED_EVENT` notification (if enabled). In SCTP notifications are retrieved using a weird `recv` call.

> Note also that "message" is not a QUIC concept; I'm assuming you're talking about smallish single-use streams, but there are other ways to encode messaging in QUIC and perhaps that's not the one you had in mind.

Yes, sorry for the confusion. Let's say that by message I mean a set of [Transmit](https://docs.rs/quinn-proto/0.4.0/quinn_proto/struct.Transmit.html) that can be reconstructed somehow into a message by the peer. I'm thinking in terms of implementing a messaging library on top of QUIC.

> Would this be adequately served by keeping track of what application-level messages you haven't yet successfully finished at the application layer?

Yes this can be tracked by the application-level, but I don't think it should necessarily be, hear me out:
I would argue 2 levels or reliability / guarantee in messaging.
#### Transmission reliability:
This means that you can transmit messages to your peer while keeping the integrity of the messages and knowing whether the message was successfully received. [Wikipedia](https://en.wikipedia.org/wiki/Reliability_(computer_networking)) claims that TCP is reliable in regards to this definition.

#### Application reliability
This means that not only you transmitted your message but your peer processed it successfully at the application level (aka did not crash). This is necessary some times, but not always.

Both TCP and QUIC guarantee *Transmission reliability*, but only as long as the connection is valid. As soon as the connection crashes, then these guarantees are gone. I would argue that for any long running service, its only a matter of time before the connection crashes. So in this context, these transports are not reliable.

You can make these protocols reliable over time by keeping a buffer of messages and doing application level ACKs. But conceptually you are paying the overhead of *Application reliability* for *Transmission reliability*.

> An ACK confirms receipt, but it does not strongly confirm loss, especially not of data that was sent after the most recent packet referenced in the ACK.

It doesn't need to be accurate. The peer would know what message are duplicates. All that matters would be that messages that were not sent are not lost.

> but unless your messages are very large or difficult to make idempotent it would likely be faster to conservatively retransmit them without waiting for that.

If you can get ownership back of the data, you can retransmit them the next time you connect to the peer, and the peer will know what messages are duplicates etc.

**Comment by jean-airoldie** [comment]
Lets illustrate this concretely:

Lets say A is the server and B is a client. Lets say we want 100% application level reliability and you don't want to keeps the messages in your buffer for ever.
* A creates message X and keeps a copy of it (because it might be lost).
* A sends X to B.
* B receives X and processes it succesfully.
* Now B wants to tell A that it processed X so that A discard its copy of X.
* B create ACK_X to acknowledge X and keeps a copy of it (because it might be lost).
* B sends ACK_X to A.
* A receives ACK_X.
* Now wants to tell B it received ACK_X so that B discards its copy of ACK_X.
* B create ACK_ACK_X and keeps a copy of it (because it might be lost).
* B sends ACK_ACK_X to A.
* etc ...

You can't even implement application level reliability in this case. To solve that you would need to keep every message in your buffer for the duration of (at most) 2 keepalive interval, just to be sure you can discard them.

**Comment by jean-airoldie** [comment]
Alternatively, lets say message are not lost on connection error this becomes:

* A creates message X and keeps a copy of it (in case B crashes).
* A sends X to B.
* B receives X and processes it successfully.
* B create ACK_X to acknowledge X.
* B sends ACK_X to A.
* A receives ACK_X and discard X.

This is because messages cannot be lost.

**Comment by Ralith** [comment]
Thanks for the details!

> Basically packets that cannot be routed are returned to the user using a SCTP_SEND_FAILED_EVENT notification (if enabled).

I see; that's an interesting feature. Something analogous in QUIC would unfortunately have to be much more complex, because application data may be fragmented and acknowledged in arbitrary ways. For example, a stream might be split into ten parts with arbitrary boundaries, and the peer might conceivably only acknowledge every other one. It's difficult for me to imagine an application making much use of the remaining fragments.

An implementation could be modified to store acknowledged data until the entire stream is acknowledged, but this is unappealing as it would entail an arbitrarily large increase in memory requirements.

> Let's say that by message I mean a set of Transmit that can be reconstructed somehow into a message by the peer.

This is unfortunately not a useful notion of message. QUIC's loss recovery machinery operates in terms of information, not packets. If you retransmitted a packet within the scope of a single connection, it would be immediately discarded by the peer as an IP error, or if from a prior connection, discarded as inauthentic.

> But conceptually you are paying the overhead of Application reliability for Transmission reliability. If the transport already does this, why discard the data and force the user to pay the price of 2 ACKs (transport + application) for each messages?

If I understand correctly, your objective is to obtain "transmission reliability" across connection loss. You don't need a second layer of ACKs to do this. If your application messages are transmitted as single-use streams (a mechanism which provides easy reliable unordered delivery of arbitrary-sized messages), then any good QUIC implementation, Quinn included, will notify the application when a stream has been received in full by the peer's transport layer, at which point the application can discard the message. Otherwise, if the connection is lost, the message can be sent anew once reestablished. If the peer determines that the message is redundant, it can accept it and do nothing.

**Comment by Ralith** [comment]
Note that the type of application-layer acknowledgements you describe, indicating that the receiver has fully processed a message, have different dynamics than transport-layer acknowledgements, which are necessarily concerned only with whether sent data was physically received. I'd suggest using bidirectional streams to implement completion notifications of that form. The same similar strategy for recovering from connection loss applies. If the receiving application determines that a message retransmitted by the sending application is redundant, then it can send the notice of processing completion immediately.

**Comment by Ralith** [comment]
Your code might look something like:
```rust
let (mut send, mut recv) = conn.open_bi().await?;
send.write_all(&msg.data).await?;
send.finish().await?;
recv.read_to_end(usize::max()).await?;
message_queue.remove(&msg.id);
```

**Comment by jean-airoldie** [comment]
>  If your application messages are transmitted as single-use streams [...] will notify the application when a stream has been received in full by the peer's transport layer, at which point the application can discard the message.

That's the kind of functionality I'm looking for. Does this use of single-use stream have significant overhead?

**Comment by Ralith** [comment]
Single-use streams are the recommended way to implement messaging on top of QUIC. Streams are *extremely* cheap; they can be created en masse with no communication with the peer, and consume comparable space on the wire to a naive TCP length-delimited scheme.

**Comment by jean-airoldie** [comment]
Cool, that's exactly what I needed. I still need do some benchmarking, but this is looking rather promising. The pluggable crypto is a really nice abstraction.

I guess I'll read the QUIC RFCs.

Thanks for your time!

**Comment by Ralith** [comment]
Glad I could help! Note that we haven't invested much effort in optimizing Quinn so far aside from trying not to do anything breathtakingly stupid, but we are interested in supporting high-performance use cases. PRs with benchmarks, especially poorly performing ones, would be much appreciated!

**Comment by jean-airoldie** [comment]
> PRs with benchmarks, especially poorly performing ones, would be much appreciated!

I'll see what I can do.
