### ISSUE TITLE
Client and Server examples don't work

### ISSUE THREAD

**Issue by NULLx76** [djc/quinn#457]
When I run the server and client with
`cargo run --example server ./ --listen 127.0.0.1:4433`
and
`cargo run --example client https://localhost:4433/cargo.toml` 

I just get a bunch of retransmits and eventually the client times out.
I get the same retransmit messages when I run the benchmark.

Am I doing something wrong or is this a bug?

**Comment by Ralith** [comment]
At a guess, your OS may not support dual-stack sockets. The client example binds to IPv6, so try binding the server to `[::1]:4433` and using that in place of `localhost` to be sure.

**Comment by NULLx76** [comment]
Yeah running the server on ipv6 works, although I do have to use `localhost` as it tries to do a dns lookup. Thanks!
