### ISSUE TITLE
Retrieve a connection from a `ConnectionError`

### ISSUE THREAD

**Issue by jean-airoldie** [djc/quinn#462]
I would like to be able to retrieve a `Connection` handle (or a reference to a connection handle) from a failed read or write future.

My use case is that I have several write futures from several distinct connections which are all pushed to the same channel. The receiver from this channel receives the resolved futures.
If the receiver receives an error, meaning a write operation failed, I want to be able to pinpoint which `Connection` caused this error.

Sure I could use a different channel for every connection, or attach a `Connection` to every future manually using a future combinator, but from what I understand, since all read and write futures hold a reference to a stream, which holds a reference to a `ConnectionRef`, this would be possible to implement at no additional cost.

So what about making `ConnectionError` a struct with a `Connection` and a `ConnectionErrorKind`?

**Comment by Ralith** [comment]
What do you plan to do with the `Connection`? A `ConnectionError` indicates that the connection has been completely lost, so it shouldn't be very useful at that point.

**Comment by jean-airoldie** [comment]
I only need to retrieve the `Connection` so that I can mark it as dead. So for instance, say I kept a `HashSet` of active connection, I would use this connection to remove it.

**Comment by jean-airoldie** [comment]
In other words, while the connection is dead, I can still use the `Connection` as a group id for write operations that failed.

**Comment by Ralith** [comment]
`Connection` does not implement `Eq` or `Hash`, though. There's also nothing wrong with trying to remove something from a `HashSet` and finding that it's already been removed.

**Comment by jean-airoldie** [comment]
> Connection does not implement Eq or Hash

Right I missed that. But I could use the socket address associated with the connection.

> There's also nothing wrong with trying to remove something from a HashSet and finding that it's already been removed.

Yes I meant that using a `HashSet` means you can remove something at most once.

**Comment by jean-airoldie** [comment]
What about returning the `SocketAddr` of the peer in the `ConnectionError`?

**Comment by Ralith** [comment]
`SocketAddr`s don't uniquely or stably identify a QUIC connection; one `SocketAddr` can host multiple distinct connections, and clients can migrate to new addresses.

I find a [`DenseSlotMap`](https://docs.rs/slotmap/0.4.0/slotmap/dense/struct.DenseSlotMap.html) (or a [`Slab`](https://docs.rs/slab/0.4.2/slab/struct.Slab.html), if you don't need iteration) is a good way to keep track of peers at the application layer. That gives you a stable internal identifier that you can pipe around however you like.

**Comment by jean-airoldie** [comment]
> I find a DenseSlotMap (or a Slab, if you don't need iteration) ...

Nice thanks, I've been looking for something like this.

However the problem with something like this is that I lose the nice thread safety of the `Connection`. If I used the `DenseSlotMap`, I would have to put it in a rwlock, or use some other concurrent data-structure. I'll look at the source to try to understand why `Connection` can't implement `Eq` or `Hash`.

**Comment by Ralith** [comment]
Those data structures would serve a similar role to the `HashSet` you envisioned, which would need just as much (or as little) synchronization. Remember that you can still clone the `Connection` and pass it around elsewhere as much as you like.

You can also standardize your clean-up logic by kicking it off when the `ConnectionDriver` future completes, rather than potentially from every single callsite.

**Comment by jean-airoldie** [comment]
> Those data structures would serve a similar role to the HashSet you envisioned, which would need just as much (or as little) synchronization. Remember that you can still clone the Connection and pass it around elsewhere as much as you like.

What I would do instead is assign a monotonically increasing id for each new connection and implement `Eq` and `Hash` in terms of this id. This way I don't need any data structure at all. Any reason why this would not be used in `quinn` directly? You could use a monotonically increasing global AtomicU64 to assign a unique id to each connection.

> You can also standardize your clean-up logic by kicking it off when the ConnectionDriver future completes, rather than potentially from every single callsite.

Thanks for the advice.

**Comment by Ralith** [comment]
> What I would do instead is assign a monotonically increasing id for each new connection and implement Eq and Hash in terms of this id. This way I don't need any data structure at all

If you don't need to store your connections in a data structure, what do you need to impl `Hash + Eq` for?

> Any reason why this would not be used in quinn directly?

Because it's not necessary for quinn or useful for most applications.

**Comment by jean-airoldie** [comment]
> If you don't need to store your connections in a data structure, what do you need to impl Hash + Eq for?

Lets say I use one active connection at a time. If I have a write error then this means that my current `Connection` is dead (and so are the other components of the connection). What I then do is create a new connection to replace the old one. Once this is done I receive another write error. However unless `Eq` is implemented, I cannot know whether this write error was associated to the old dead connection or the new connection.

**Comment by jean-airoldie** [comment]
Moreover, now that I think about it, `std::sync::Mutex` could implement `Eq` by comparing the address of the `Box` that holds the mutex since it cannot be moved.
https://doc.rust-lang.org/src/std/sync/mutex.rs.html#117

**Comment by Ralith** [comment]
If you handle the connection error once and for all in the driver task, then you don't need to worry about deduplication, because there's always exactly one of those.

**Comment by jean-airoldie** [comment]
Good point.

**Comment by jean-airoldie** [comment]
Cool so checking if any of the `ConnectionDrivers` died before doing IO solves my problem. Thanks!
