### ISSUE TITLE
Estimating incoming stream size

### ISSUE THREAD

**Issue by jean-airoldie** [djc/quinn#463]
I am using individual uni & bi streams to deliver messages. I would like to know the size of an incoming `RecvStream` before it is fully received. This would have two main benefits:
* I could allocate sooner for the message buffer, [as opposed to after it was fully received](https://docs.rs/quinn/0.4.0/src/quinn/streams.rs.html#373)
* This would allow me to know the total size of multiple concurrent read streams before they are finished (and allow me to control the size of my incoming message queue).

From what I understand when receiving from a stream (bi & uni), the exact size is not known until the stream enters the ["Size Known" state](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#stream-recv-states).

So my plan was to add a size prefix to my messages inside the streams. Then from the receiver's side I can `read_exact` this size prefix followed by a `read_to_end` using this prefix as a `size_limit`. Moreover, I would used a modified `read_to_end` that preemptively allocates the buffer using the `size_limit`.

Is there a better way estimate the size of a incoming stream?

**Comment by djc** [comment]
As the linked section 3.2 explains, "size known" happens when the final frame of the stream arrives. Since QUIC supports streams for which the size is not known in advance, communicating stream sizes is indeed left to the application layer (as far as I know).

**Comment by djc** [comment]
(For controlling the size of your incoming message queue, there *are* other mechanisms.) Have a look at section 4 about [Flow Control](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#flow-control).

**Comment by jean-airoldie** [comment]
The `MAX_STREAM_DATA` seems really circumstantial, but the `MAX_DATA` would be helpful. Are there any plans to support these mechanism?

**Comment by djc** [comment]
What makes you think Quinn doesn't? Look at `TransportConfig::receive_window`.

**Comment by jean-airoldie** [comment]
I missed that. Is there a way to increase this `receive_window` over time? From what I read `MAX_DATA` is credit based an allow you to increase over time. So you could use it to advertise the space available in your incoming queue as it frees.

**Comment by jean-airoldie** [comment]
In case I wasn't clear, I'm talking of a application level incoming buffer in which streamed are read and their content is stored.

**Comment by djc** [comment]
I don't think we have the APIs in place to change the `receive_window` over time. @Ralith?

**Comment by Ralith** [comment]
`receive_window` is not sent literally as `MAX_DATA`; it's a specification of the total amount of application data that may be sent by the peer before the local application consumes any. That means we send a new `MAX_DATA` frame whenever the local application consumes some data, reflecting the freed space, though in the future we may reduce the frequency of these messages for efficiency.

**Comment by jean-airoldie** [comment]
What do you mean by `consume`?

From what I understand, from the receiver's side its impossible to know ahead of time the size of an incoming message until it is fully received (or enters the size known state). So how can this be enforced?

Ideally I would want `receive_window` to reflect the size of my application's incoming buffer.

**Comment by Ralith** [comment]
When the application reads data, the transport no longer needs to store it; hence the data is said to be "consumed" by the application. You should `receive_window` to the maximum amount of data you want the transport to buffer before your application reads it. Usually this is the bandwidth-delay product, plus some margin for error.

**Comment by jean-airoldie** [comment]
I guess I don't in see in what context the transport buffers data. Does the transport start to buffer data from an incoming stream even before the user receives said stream?

**Comment by Ralith** [comment]
Data is buffered by the transport for the period between when it is received by the transport and when it is read by the application.

**Comment by jean-airoldie** [comment]
Makes sense.

So this means I can't use the `receive_window` to limit the size of my application incoming buffer. I have to do it at the application level by size prefixing the streams. Its only used to control the transport incoming buffer.

Thanks again!
