### ISSUE TITLE
Provide a better error type than `()` for `Incoming`

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#509]
Currently, I have no idea what to do if `Incoming::poll_next()` returns `Ready(Err(()))`.

**Comment by Ralith** [comment]
This is fixed in master, where `Incoming` has no error case at all: https://github.com/djc/quinn/blob/master/quinn/src/endpoint.rs#L355

**Comment by DemiMarie-parity** [comment]
Agreed, closing.
