### ISSUE TITLE
Factor out common error handling code

### ISSUE THREAD

**Issue by djc** [djc/quinn#51]
There is a lot of repetition in error handling code in methods of the `Connection` impl. There are multiple ways this could be improved, in increasing order of complexity:

* Factor them out into one or more utility methods
* Create a nice error type that this returned to `Endpoint` so it do the proper handling in one place
* In doing so, make it so that the `Connection` no longer has to know its `ConnectionHandle`

@Ralith does that make sense to you? @twilco this is a little more open-ended, but I think you can ramp it up by taking it one step at a time to gain some familiarity with the issues.

**Comment by Ralith** [comment]
This would be good to have; in particular, it may be possible to refactor `Connection::handle_connected_inner` to return a `Result<State, ConnectionError>` or something similar, with `Endpoint` worrying about how to convert that into a state transition and generate any necessary I/O and events.

Removing the `ConnectionHandle` goes a bit beyond the above, but will certainly be an easier task once that's done.

**Comment by twilco** [comment]
Okay, I'll work on refactoring `Connection::handle_connected_inner` to return a `Result<State, ConnectionError>` instead of `State`.  It looks like there is already a `ConnectionError`, so perhaps we can make use of that.
