### ISSUE TITLE
H3 interop server

### ISSUE THREAD

**Issue by stammw** [djc/quinn#522]
We now should be able to run H3 on our interop endpoint. 

Could the code of what's currently running on @Ralith be shared somewhere, so I can update it with a H3 server?

Would it be interesting to maintain a special branch for it and use the CI to deploy it? I don't really see how hard it can be, if it worth the effort.

**Comment by djc** [comment]
Would be nice to just put it as a binary in the interop crate, I guess.

**Comment by Ralith** [comment]
I'm just running the quinn server example, with a separate instance in stateless retry mode. A dedicated interop server that uses ALPN to host both hq and h3 (and even stateless retries in the same process) would be good to have!

**Comment by stammw** [comment]
Some Interop server needs might go beyond the example implementation.

For example, `lsquic` endpoint responds an arbitrary length chunk of data given what it gets requested in the Url path: `http://test.privateoctopus.com:4433/123K' gets 123K. They also offer a "POST" interface in which I didn't dig for details.

At some point, we might want to offer a log-by-cid interface to other implementers like `quant`. In the end it could save us some time answering to trivial errors they have. And would encourage them to test against our endpoint.

An additional `[[bin]]` would make sense for this reason IHMO.

There is a question I have been asking myself: But, what is running on our interop endpoint exactly? I think we could store the answer in a tag on the repo. With some courage (and time, obviously), we could even make the CI push the bin on a server so it would automate and guaranty we stay in sync.

**Comment by Ralith** [comment]
Splitting the interop server out would also let us simplify the example server some, which seems like a good idea.

**Comment by stammw** [comment]
Closed via #584
