### ISSUE TITLE
Make interop client compatible with non-HTTP/0.9 endpoints

### ISSUE THREAD

**Issue by stammw** [djc/quinn#523]
Running the interop client against some endpoints gets most of items failing because they don't support HTTP/0.9 anymore. 

Update `interop/src/main.rs` to fix that and make fix H3 if it doesn't match the needs for it.

**Comment by Ralith** [comment]
There might also be other impls that don't support H3, so taking a flag for which to use could be prudent.

**Comment by stammw** [comment]
This also ha been fixed in #551
