### ISSUE TITLE
Automate interop client running

### ISSUE THREAD

**Issue by stammw** [djc/quinn#524]
The interop client could be run on all the known implementations at once. 

For example, we could maintain a list of urls in a yaml file, and add a cli flag to `interop/src/main.rs` to make it run tests against each of them, and output a list of results. 

Feedback for new changes would then be a lot faster to obtain. It could also be run by the CI.

**Comment by djc** [comment]
Not sure about running this in CI. Would be nice to have, though.

Can probably just stuff the list of endpoints in a `const` rather than having the YAML, since it's just us changing it.

**Comment by Ralith** [comment]
Hardcoding a list of peers to test sounds like a great idea! I've gotten pretty lazy about clientside interop testing and this would make it trivial to keep up.

**Comment by Ralith** [comment]
This was fixed by #551, right?

**Comment by stammw** [comment]
Yes it was!
