### ISSUE TITLE
My library review while I get to grasp QUINN.

### ISSUE THREAD

**Issue by TimonPost** [djc/quinn#533]
Great project! As I browse through this library and try to get a grasp on it so that I can start contributing, I will post my findings here, like things, I find confusing, not clear or strange. This is purely personal taste and can also be incomprehension of choices made. Think of it as feedback and insight from someone who tries to understand the library from the outside. It is easy for a developer to get used to its own code.

1. The difference between interop/quinn/quinn-h3/quinn-proto is not clear.
2. Same types in quinn-proto and quinn:
      * `endpoint.rs`: quinn-proto\src & quinn\src
      * `streams.rs`: quinn-h3\src & quinn-h3\src\proto & quinn-proto\src & quinn\src
      * `connection.rs`: quinn-proto\src & quinn-h3\src & quinn\examples & quinn\src\ & quinn-h3\src
      * `frame.rs`: quinn-h3\sec & quinn-h3\proto\ & quinn-proto\src
      * `header.rs`:  quinn-h3\src & quinn-h3\src\proto
3. Complex functions noticed by clippy and files that are very big like: quinn-proto/connection.rs. This is difficult to graps.
5. Public types are missing documentation. And is difficult to see what things do what.
6. Inconsistency in the documentation.   
    * With, without a  '.', 
    * Plural/vs singular
    * No documentation at all
7. Inconsistency with tests. 
    * Naming is not clear like: `datagram_window`
    * Naming is inconsistent and there does not seem to be a common pattern like test_function_retuns_something.
8. It can be personal flavor, there are so many places were enters are left away between code, this makes it in my eyes less readable and kind of weird looking. 

![image](https://user-images.githubusercontent.com/19969910/69784983-65a1a080-11b7-11ea-8100-fa572aca0081.png)

9. Files containing multiple types, and is not clear to read that form the file name.
10. Lot's of variables being a single character.

**Comment by djc** [comment]
1. I think it would make sense to have a short list of the crates and a high-level description of what they contain in the README.
3. If you're specific about types which are public which you found hard to grasp, we'd probably prioritize writing some documentation for them.

For the other things, these are trade-offs where we as the maintainers have made particular choices. If you have concrete suggestions about how to make the trade-off differently, we can discuss it, but be prepared to come with pretty strong arguments.

**Comment by Ralith** [comment]
Thanks for sharing your feedback! Closing since I think we've addressed the main actionable things here; feel free to open specific issues for future non-style-related matters if necessary.
