### ISSUE TITLE
Game-oriented networking library wrapping around quinn naming

### ISSUE THREAD

**Issue by LaylConway** [djc/quinn#538]
I was suggested to open an issue about this to open up discussion.

I'm writing a library on top of quinn that provides basic game networking functionality, similar to libraries such as RakNet, but accessible from a synchronous game loop. I'm figuring this library may be useful to other people writing networked games in the Rust ecosystem, and benefit from contributions and code reviews. That's why I'm aiming at publishing this (right now fairly small) library to crates.io.

I'm hoping to call this library "harlequinn", and I wanted to open up discussion on if anyone has objection to this, because of the naming including "quinn".

**Comment by Ralith** [comment]
No objection from me. @djc, @stammw?

**Comment by stammw** [comment]
I don't have any objection. Have fun !

**Comment by djc** [comment]
Sounds good to me. Thanks for asking!
