### ISSUE TITLE
quinn-proto: document when a stream has been destroyed

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#544]
From the quinn-proto documentation, it is not clear when further `Event`s are guaranteed not to mention a particular `StreamId` unless the `StreamId` has been subsequently opened again.  This is crucial for my code, which will panic if an event is received for an unknown `StreamId`.

Is there a way to immediately destroy a stream?  I don’t care if the stream is immediately destroyed at the protocol level, but I do need to know when I can release all associated state.

**Comment by Ralith** [comment]
Thanks for the issue! We should definitely be clearer about this. The general rule of thumb is that quinn-proto discards state for a stream only after the stream is dead for state machine purposes *and* the caller has consumed a notification of this, but we should be able to pin this down more concretely.

**Comment by Ralith** [comment]
Note that stream IDs are never reused, incidentally.

**Comment by DemiMarie-parity** [comment]
Can I assume that:

* Once `finish` has succeeded, a stream will not report itself as open for writing?
* Once `stop_sending` has succeeded, a stream will not report itself as open for reading?

**Comment by Ralith** [comment]
> Once finish has succeeded, a stream will not report itself as open for writing?

On inspection, I don't think this is the current behavior, but we can easily provide it. #545 should correct that, and I'm happy to consider failure to do so a bug. The same guarantee should be provided for `reset`.

> Once stop_sending has succeeded, a stream will not report itself as open for reading?

`stop_sending` is purely advisory to the peer; it does not influence the local endpoint behavior at all. A well-behaved peer should usually reset the stream immediately upon receiving the message, but even then data that's already in-flight may still be delivered. Hence you should either tolerate readable events for forgotten streams, or retain state until reading produces an `Ok(None)` or `Err(ReadError::Reset { .. })`.

**Comment by Ralith** [comment]
@DemiMarie-parity, does #545 clarify things sufficiently?

**Comment by DemiMarie-parity** [comment]
@Ralith yes, it does.
