### ISSUE TITLE
TransportParameters are hidden

### ISSUE THREAD

**Issue by survived** [djc/quinn#565]
Although `quinn-proto` provides generic [Session trait](https://docs.rs/quinn-proto/0.5.0/quinn_proto/crypto/trait.Session.html), [transport_parameters](https://docs.rs/quinn-proto/0.5.0/quinn_proto/crypto/trait.Session.html#tymethod.transport_parameters) method signature holds unexposed TransportParameters. What's the point of having generic Session trait if I'm not able to make my own implementation?

I'm looking for better way to make nQUIC implementation and I believe implementing Session trait is what I need.

**Comment by djc** [comment]
I think that's just an oversight, since we don't have any third-party `Session` implementations. Patches welcome, or I'll fix it up tomorrow.

**Comment by djc** [comment]
See #568.
