### ISSUE TITLE
Expose which timers are idle and loss detection

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#574]
The documentation for `quinn_proto::generic::Connection` indicates that certain timers have special meaning.  I currently use an ugly hack (hard-coding numbers) to determine which timer is which.  Applications should be able to tell if a timer is the idle or loss-detection timer.

**Comment by Ralith** [comment]
What's your use case? These are intended to be implementation details.

**Comment by DemiMarie-parity** [comment]
Performance.  I want to avoid polling for events that cannot possibly happen.

**Comment by Ralith** [comment]
Such as?

**Comment by DemiMarie-parity** [comment]
I only need to poll for outgoing packets if the LossDetection timer expired.  I only need to poll for application-facing events if the idle timer expired.

**Comment by Ralith** [comment]
Those aren't guarantees we want to make on the public API. For example, we might in the future propagate the detection of lost application datagrams to the application, which would constitute an application-facing event on loss detection timeout. I see there's some outdated comments from before we made timers opaque; I'll update those.

**Comment by DemiMarie-parity** [comment]
Can we reduce the number of timers down to 1, with `quinn_proto` handling the bookkeeping internally?

**Comment by Ralith** [comment]
We could, and I wouldn't mind the simplification of the API. I'm not sure there's even a hypothetical advantage to the way it works presently; the thinking was that you might have one great big pool of timers with a single layer of multiplexing, but that's not how it worked out.

**Comment by DemiMarie-parity** [comment]
@Ralith I agree.  That’s what quiche does.  Ideally, we would have just one timer per endpoint.  The current design strongly encourages having a background task per connection, which is annoying.
