### ISSUE TITLE
Stateless reset token comparison should be constant-time

### ISSUE THREAD

**Issue by Ralith** [djc/quinn#585]
Our current implementation is likely vulnerable to a timing attack as discussed in [the current draft](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#name-detecting-a-stateless-reset). The easiest fix is to drop in a constant time comparison. Is there a popular crate for such that's a suitable hard dep for quinn-proto? We went to some effort to make `ring` not strictly required already.

**Comment by djc** [comment]
There's [subtle](https://crates.io/crates/subtle) and [constant_time_eq](https://crates.io/crates/constant_time_eq) that I know of.
