### ISSUE TITLE
quinn does not update timers when one is already active

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#587]
`quinn` currently polls for timer updates only when it has no current timer or its current timer expires.  This contradicts the `quinn-proto` documentation.

**Comment by Ralith** [comment]
This is in fact incorrect, not just undocumented. Thanks for the catch!

**Comment by DemiMarie-parity** [comment]
You’re welcome!  I am using git HEAD in libp2p-quic and found that as I was looking through the recent breaking changes.
