### ISSUE TITLE
Document how to wait for all pending traffic to be delivered

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#588]
How can I wait for all pending traffic to be delivered?  I need to know when I can safely close a connection,

**Comment by Ralith** [comment]
This is accomplished (for outgoing data) by calling `finish` on all outstanding streams and waiting for those operations to complete (via the future in `quinn`, or the `StreamFinished` event in `quinn-proto`). Would it help if this was called out more specifically in the documentation for `close`?

**Comment by DemiMarie-parity** [comment]
Yes, it would.  That said, I would also like to be able to verify that all pending traffic on a particular stream has been acknowledged, while still potentially being able to send data on that stream.

**Comment by Ralith** [comment]
> I would also like to be able to verify that all pending traffic on a particular stream has been acknowledged, while still potentially being able to send data on that stream.

This came up in #519 and it sounded like you didn't need it after all. Did that change?

**Comment by DemiMarie-parity** [comment]
Not really.  It would be an interesting feature, but I cannot think of any use-cases for it, so it might not be worth implementing.

**Comment by Ralith** [comment]
Thanks for confirming. I agree that it's an interesting idea, but in lieu of a concrete requirement I come down on the side of keeping quinn as simple as possible.
