### ISSUE TITLE
How would one handle SNI with multiple domains?

### ISSUE THREAD

**Issue by tuboythers** [djc/quinn#595]
Hello,

I am expressing big interest in your crate and have vaguely gone through the documentation and examples, but one thing is not very clear for me. Usually, one might want to create a web server which handles requests for multiple domains, each with their own certificate, but I cannot see a way of doing this with `quinn`, or am I wrong?

Based on your server example, you first create the `ServerConfig`: 
```if let (Some(key_path), Some(cert_path)) = (&options.key, &options.cert) {
... server_config.certificate(quinn::CertificateChain::from_certs(vec![cert]), key)?;
    }
```

And then you create the `Endpoint` using that config:
```
let mut endpoint = quinn::Endpoint::builder();
    endpoint.listen(server_config.build());
```

And finally you instantiate the listener and start accepting new connections: 
```
let mut runtime = Builder::new().threaded_scheduler().enable_all().build()?;

    let (endpoint_driver, mut incoming) = {
        let (driver, endpoint, incoming) = runtime.enter(|| endpoint.bind(&options.listen))?;
        info!("listening on {}", endpoint.local_addr()?);
        (driver, incoming)
    };
runtime.spawn(async move {
        while let Some(conn) = incoming.next().await {
...
handle_connection(root.clone(), conn).unwrap_or_else(move |e| {
                    error!("connection failed: {reason}", reason = e.to_string())
                }),... Ok(())
}
```

And then you handle the streams with the `handle_connection fn`:
```
async fn handle_connection(root: Arc<Path>, conn: quinn::Connecting) -> Result<()> {
    let quinn::NewConnection {
        driver,
        connection,
        mut bi_streams,
        ..
    } = conn.await?;
...
```

All of the above has been taken from your `server.rs` example. So, my question is, with multiple domains you can only know the SNI hostname once the connection has been created and socket established; with your crate, how would one go about doing TLS handshake with the appropriate SSL Certificate for that SNI Hostname (domain) once the connection is established, and not beforehand like it is now?

With Rustls and Tokio you first spawn the `TcpListener`, then start accepting connections over `TcpStream` and then you create a `TlsSession` from that stream, and from then you can read the encrypted data in plaintext through that `TlsSession` and write back to it to the encrypted stream. All of this happens once the `TcpSocket` is created and if one would like, they could attach a different SSL Certificate & Key pair per `TcpStream`.

Maybe I've got something wrong or missed something, but how would one accomplish the same thing with your crate? Any assistance/guidelines/examples would be highly appreciated!

**Comment by Ralith** [comment]
Hi, thanks for your interest! You can supply the correct certificate using the same mechanism you would in TCP, i.e. by configuring the rustls [cert_resolver](https://docs.rs/rustls/0.16.0/rustls/struct.ServerConfig.html#structfield.cert_resolver) used by the server. The rustls `ServerConfig` is exposed in the `crypto` field of quinn's own `ServerConfig`.

What I think we *are* missing is a way to actually look up what was negotiated, similar to the existing `protocol` accessor. I'll see about drafting a fix for that.

**Comment by tuboythers** [comment]
You are actually right! In my current implementation I've been creating a new `rustls::ServerConfig` for each new `TcpStream` instanced and I've been pretty much doing `set_single_cert` all time around, haha, so rid.

It was only after you mentioned the `cert_resolver`, that I actually sat and read through the Rustls documentation. So now it is time to sit and experiment with Quinn, hopefully that goes fine without any issues.

Thank you!

**Comment by djc** [comment]
If you do run into further issues, please reach out and let us know!
