### ISSUE TITLE
Document transmit vs receive order

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#600]
Is it necessary to receive packets before transmitting them?  Also, is it necessary to marshal all packets to the endpoint for transmission?

**Comment by Ralith** [comment]
I'm not sure it's feasible to document all the things you're not required to do. Ordering shouldn't matter so long as you process everything in the end (i.e. before sleeping).

**Comment by Ralith** [comment]
Closing since I'm not sure this is actionable; if there are specific statements you think would make this clearer, a PR would be welcome.
