### ISSUE TITLE
Test the case where the server opens the first stream

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#601]
My tests for libp2p-quic have the server open the first stream.  This results in intermittent hangs that I have not been able to debug.  Is this tested?

**Comment by Ralith** [comment]
Tests that begin with the server opening a stream include `zero_rtt` and `read_after_close` in quinn/src/tests.rs. Note that stream handling is very symmetrical, so we don't expect directional differences in behavior. If you provide details for what exactly you're doing, and trace-level logs, we may be able to help diagnose the error. Bear in mind that opening a stream does not notify the peer until you actually do something with the stream, as [documented](https://docs.rs/quinn/0.5.2/quinn/struct.Connection.html#method.open_uni) on the relevant high-level API methods.

**Comment by DemiMarie-parity** [comment]
@Ralith I have no problem providing logs, but as I use `quinn-proto` instead of `quinn` there will be only logs from my code, which is https://github.com/DemiMarie-parity/rust-libp2p/tree/d4c6ab136975380c0027db71fc451b5dd64115ee.  To reproduce, run the executable produced by `cargo test --release` in a loop; it will eventually panic.

**Comment by Ralith** [comment]
> as I use quinn-proto instead of quinn there will be only logs from my code

quinn-proto makes extensive use of `tracing` logs, and they can be captured the same way you would when using quinn.

**Comment by DemiMarie-parity** [comment]
@Ralith I hope I am not asking too much, but the documentation for the `tracing` crate is not particularly helpful.  I have set up an env filter, but get no output.

**Comment by Ralith** [comment]
The easiest approach is to call [`tracing_subscriber::fmt::init`](https://docs.rs/tracing-subscriber/0.2.0-alpha.4/tracing_subscriber/fmt/fn.init.html), then set `RUST_LOG=quinn-proto=trace` in the environment. You might have missed the second part?

**Comment by Ralith** [comment]
Closing since this case is indeed covered; feel free to open a new issue if you have logs indicating incorrect behavior.
