### ISSUE TITLE
Is it okay to drop outgoing packets?

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#602]
Is it okay to drop an outgoing packet if there are too many packets waiting to be sent?  I plan on having a fixed-size ring buffer for outgoing packets.  The goal is to avoid both deadlocks and excessive memory consumption.

**Comment by Ralith** [comment]
UDP packets can be dropped at any time, by any path element; that's the nature of UDP. Dropping too many packets will adversely affect connection performance, of course. I recommend carefully considering buffer size with respect to the bandwidth-delay product of the links you're targeting.

**Comment by burdges** [comment]
In fact QUIC provides its own internal retry mechanism, not too unlike the TCP mechanism.

Rateless error correcting codes like [RaptorQ](https://en.wikipedia.org/wiki/Raptor_code) and [online codes](https://en.wikipedia.org/wiki/Online_codes) provide an interesting direction too.  I think QUIC's retry mechanism never uses cross packet error correction.  There are extensions like [QUIC-FEC](https://export.arxiv.org/pdf/1904.11326) that do this for special situations, but afaik nothing really compelling.

**Comment by Ralith** [comment]
Yeah, forward error correction was among the features deliberately punted to future work in the interest of making 1.0 become a thing in finite time.
