### ISSUE TITLE
Remove the endpoint/connection messaging

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#605]
This is annoying to deal with, and [Cloudflare’s quiche](/cloudflare/quiche) doesn’t seem to have it.

If there is a good reason for it (which there may very well be), that reason should be documented.

**Comment by Ralith** [comment]
Coordination between connections and their endpoint is necessary; see the RFC for details. Quiche makes sacrifices in terms of capability and by externalizing substantial complexity to the user, which is inconsistent with quinn's goals. Patches to make it less annoying are welcome.
