### ISSUE TITLE
Run tests in a tight loop

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#607]
When working on libp2p-quic, I found many bugs that did not reproduce unless I ran the test case thousands of times.  This is not practical to do by hand, but is trivial to automate, so it might be beneficial for some tests.

**Comment by DemiMarie-parity** [comment]
I just found a race condition in my code that did not appear until after over 100,000 runs.

**Comment by Ralith** [comment]
Closing in favor of #675, which involves running many iterations in an environment that's more likely to manifest issues.
