### ISSUE TITLE
Document exactly when `UnknownStream` will be returned

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#615]
It would be nice to know exactly when `UnknownStream` will be returned.

**Comment by Ralith** [comment]
The current documentation is pretty specific. Can you elaborate on what's unclear?

Broadly speaking, it always indicates that you're operating on a stream half after having already been given information indicating that it should no longer be used.

**Comment by DemiMarie-parity** [comment]
I am wondering if I can rely on `UnknownStream` being returned, or if it always indicates a bug in the caller.  There are other similar cases, such as calling `Connection::write` or `Connection::finish` on a closed connection.

I can, of course, keep track of this state explicitly, but it feels wrong to do so if it is not required.

**Comment by Ralith** [comment]
You are free to rely on the documented behavior; that is why it's documented. You should consider structuring your application such that you're not holding onto references to resources that you were already notified have been destroyed, though.

**Comment by DemiMarie-parity** [comment]
I am writing a library (libp2p-quic) that wraps quinn-proto.  If `UnknownStream` is returned, that indicates a bug in the caller, so I log it at `error` level.  Thank you.
