### ISSUE TITLE
tls::ParseError

### ISSUE THREAD

**Issue by dirvine** [djc/quinn#616]
The tls mod is private right now. This gives me an issue trying to convert the errors from tls such as ParseError. I am not sure it's as simple as making tls pub, but would appreciate your thoughts here.

**Comment by Ralith** [comment]
Good catch, thanks! This should probably be reexported from the root, perhaps as `TlsParseError`.

**Comment by dirvine** [comment]
Many thanks? If it's done would it be possible to have a patch release?

**Comment by djc** [comment]
I've just published 0.5.3 which includes this fix.

**Comment by dirvine** [comment]
Ah, thank you so much. Really appreciated.

**Comment by dirvine** [comment]
Ah, I am really sorry, but there are also some webpkil::error::Error issues as well. Should I raise another issue?

**Comment by Ralith** [comment]
You can get that by adding an explicit dependency on webpki 0.21 to your own crate.

**Comment by dirvine** [comment]
Thanks, that is what we will do.
