### ISSUE TITLE
If `Connection::finish` is called when there is no pending data, `StreamFinished` is emitted too soon.

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#617]
`Connection::finish` causes `StreamFinished` to be emitted after all data has been acknowledged, and causes the `fin` flag to be set on the last packet in the stream that has not already been sent.  However, this is not enough to ensure the peer is notified of the shutdown.  If `Connection::finish` is called when there is no data that needs to be sent, it needs to send a packet that has `fin=true` and `len=0`, and wait for it to be acknowledged before emitting `StreamFinished`.  This only happens intermittently in my tests because there is usually unsent data when `Connection::finish` is called.

Protocols that have explicit in-band close indications are not affected, as the peer knows that the stream has been finished by other means.  I believe that HTTP/3 is such a protocol.

**Comment by Ralith** [comment]
Thanks for investigating this! The desired behavior you describe is how it's intended to work, which seems to already be reflected in [the relevant code](https://github.com/djc/quinn/blob/master/quinn-proto/src/spaces.rs#L143-L154), so it's not immediately apparent to me what might be going on here.

**Comment by DemiMarie-parity** [comment]
That code indeed looks correct, thanks!  The real problem appears to be in this code:

https://github.com/djc/quinn/blob/8e53321bfc72ab6aa47f226bd76b475f3476cce9/quinn-proto/src/connection.rs#L511-L518

That code only checks that all data has been delivered, and does not check that a final empty STREAM frame was acknowledged by the peer.  My code receives the `StreamFinished` message, concludes that the all data has been acknowledged, and closes the connection before the empty STREAM frame can ever be sent.  The peer thus never receives the end-of-file indication, which results in the behavior I observed in #604.

**Comment by Ralith** [comment]
Well spotted! That's definitely the bug. In fact we need both checks: zero bytes in flight *and* `fin` acknowledged, to ensure packet loss is handled correctly. I can put a fix together this weekend. Thanks a ton for digging so far into this!

**Comment by DemiMarie-parity** [comment]
@Ralith You’re welcome!  Thank you for being so responsive and helping me track this down!  Will you need help writing a regression test?

**Comment by Ralith** [comment]
I expect it'll be straightforward; just need to arrange for an acknowledgement of all outstanding data to be received after `finish` has been called but before the sender has had a chance to actually transmit it.

**Comment by DemiMarie-parity** [comment]
Will tests for packet loss also be straightforward?
