### ISSUE TITLE
Use a token to ensure that `Endpoint::accept()` is not called too many times

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#627]
Currently, it is easy to call `Endpoint::accept()` too many times, which leads to problems.  Ideally, this would be prevented at compile time.

**Comment by Ralith** [comment]
Good catch! An underflow of `incoming_handshakes` would prevent further connections from being accepted, so a bit of defensive programming here seems reasonable.

**Comment by djc** [comment]
Okay, so what exactly is it that we're trying to exert backpressure on? I'm certainly willing to accept that my intuition about the `AcceptToken` being more complex than necessary is wrong, but I'd like to understand why.

**Comment by Ralith** [comment]
The ultimate objective is to allow a server to respond to connection attempts with `SERVER_BUSY` when it cannot currently accept additional connections, rather than timing out the connection or accepting it and eventually falling over due to resource exhaustion.

**Comment by djc** [comment]
Sure. So if the `Endpoint` has a configurable fixed size buffer, that's enough, right?

**Comment by Ralith** [comment]
In the sense that `accept_buffer` is that, yes.

**Comment by djc** [comment]
So then why do we need this token business? (Sorry if you're frustrated with my slowness... I assure you I'm not intentionally dragging my feet, just trying to understand the issues here.)

**Comment by DemiMarie-parity** [comment]
To statically guarantee that `Endpoint::accept()` cannot be called too many times.  That said, I believe that there are cases where accepting multiple connections in a tight loop is needed.

**Comment by djc** [comment]
Since the `accept_buffer` size is configurable, you could always do your own token thing on the caller side, right? So then this is an argument for making the API arguably harder to use for what I perceive to be a fairly niche constraint/use case.

**Comment by djc** [comment]
(Also, calling `accept()` too many times shouldn't be an issue. We could also have `accept()` return a `Result` in the case of `incoming_handshakes` being 0 already.)

**Comment by Ralith** [comment]
Closing since I think we've fixed the biggest footgun here and it doesn't seem like anyone feels all that strongly otherwise.
