### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#633]
libp2p-quic relies on several features only found in the master branch.  It cannot be published on `crates.io` until a new `quinn-proto` release is made.

**Comment by Ralith** [comment]
I agree that it's getting to be time for this. That said, I'd like to resolve #619 first to preserve interop with other QUIC implementations, unless you're facing a hard deadline of some sort. That work may take a few weeks, as my free time is currently limited.

**Comment by djc** [comment]
Releases are pretty cheap to do, though, right? So we could just push out a 0.6 now (with release notes warning people that another release with draft 25 is coming soonish) to help libp2p.

**Comment by Ralith** [comment]
That's fine with me.

**Comment by djc** [comment]
Draft release notes: https://github.com/djc/quinn/releases/edit/untagged-40a72926ba64e0282a74 (ping @stammw, too).

**Comment by Ralith** [comment]
Looks good, thanks!

**Comment by stammw** [comment]
Good for me to! Thanks! 
(hope to find the energy for a first he release soon!)

**Comment by djc** [comment]
I'm holding off on this for a little bit to see if we can get #638 and #639 done soon.

**Comment by lionel1704** [comment]
Hi there! I see that both the issues linked above have been resolved.
Is there anything else in particular that's blocking a new release?

**Comment by djc** [comment]
#644 is in flight, and I'd like to include it. I might also want to see if more issues fall out of #650.

**Comment by djc** [comment]
Currently blocked on #650 and #670 (the latter is hopefully fixed already, but needs to be confirmed).

**Comment by djc** [comment]
This is done.
