### ISSUE TITLE
Document minimum channel sizes for connection ↔ endpoint communication

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#637]
There is a possible deadlock where the endpoint is blocked on being able to send messages to the connection, but the connection is blocked on being able to send messages to the endpoint.

**Comment by Ralith** [comment]
I don't believe a deadlock is possible, because a `Connection` must always immediately accept any incoming `EndpointEvent`.

**Comment by DemiMarie-parity** [comment]
Is it possible for an unbounded number of `ConnectionEvent`s to be queued in the `Connection`, if the `Endpoint` is slow to receive them?  That would be bad.

**Comment by Ralith** [comment]
You're free to stop polling for new ones until there's buffer space available.

**Comment by DemiMarie-parity** [comment]
What if a `Connection` is slow, and cannot receive `EndpointEvent`s fast enough?  Or can this be avoided by always polling for `ConnectionEvent`s before polling for incoming packets?

> You're free to stop polling for new ones until there's buffer space available.

Will this cause the `Connection` to buffer an unbounded amount of data internally?  The whole point of using bounded buffers is to limit the total amount of buffered data.

**Comment by Ralith** [comment]
> What if a Connection is slow

If you're processing a connection on a separate thread and using bounded channels, you should be prepared to block the endpoint if a connection is unable to make progress. I think this could be alleviated by #636.

> Will this cause the Connection to buffer an unbounded amount of data internally? The whole point of using bounded buffers is to limit the total amount of buffered data.

No, the number of endpoint events generated is bounded by the number of connection events received from the endpoint.

**Comment by Ralith** [comment]
Closing because there doesn't appear to be an issue here.
