### ISSUE TITLE
Adopt tokio_timer::DelayQueue

### ISSUE THREAD

**Issue by Ralith** [djc/quinn#64]
We're currently using an awkward heavyweight hack to schedule timers; see the `quinn` crate's `EndpointInner` struct's `timer` member for details. [`DelayQueue`](https://docs.rs/tokio-timer/0.2.7/tokio_timer/struct.DelayQueue.html) was literally purpose-built for our requirements, so let's put it to work.

**Comment by twilco** [comment]
I'd like to take a go at this one.  I'm busy the next couple days (will be at Rust Belt Rust!), and want to do some initial learning of Tokio as part of the [Tokio docs push](https://github.com/tokio-rs/doc-push), but after that I will have time to work on this.

If someone else comes across this issue and feels motivated to take it before then let me know and we can work something out 👍 .

**Comment by twilco** [comment]
Things have come up and I think I'm going to be busy for a bit, so if there's anyone else who wants to take this go for it.

**Comment by little-dude** [comment]
I'd like to work on that.

**Comment by Ralith** [comment]
Great! Feel free to hit up the gitter if you have any questions.

**Comment by little-dude** [comment]
So far so good, hopefully I'll submit a PR tonight or tomorrow :)

**Comment by Ralith** [comment]
Mooted by #264
