### ISSUE TITLE
connection example gets ApplicationClose on server incoming

### ISSUE THREAD

**Issue by djc** [djc/quinn#641]
This manifests as a panic:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" })', src/libcore/result.rs:1188:5
...
  14: core::result::Result<T,E>::unwrap
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:956
  15: connection::main::{{closure}}::{{closure}}
             at quinn/examples/connection.rs:29
```

Before 4a83c6c36120a7143a336b56cb170c660ec1091c, we got output similar to this:

```
[client] connected: id=9ae6a7365e48d4e6, addr=127.0.0.1:5000
[server] connection accepted: id=7714b6e92ba5be26 addr=127.0.0.1:49687
[server] connection lost: closed by peer: 0
```

Originally mentioned by @vjyanand in #639.

**Comment by djc** [comment]
I guess the scenario here is that the client drops the connection and the server's `EndpointDriver` notices this before delivering the incoming connection to the application, so that the server will only deliver the `ApplicationClose`, not the actual incoming.

**Comment by vjyanand** [comment]
Exactly this is what I see. Looks like the issue in the sample code, not in library
