### ISSUE TITLE
Hanging in SendStream::finish

### ISSUE THREAD

**Issue by alecmocatta** [djc/quinn#645]
[This program](https://github.com/alecmocatta/chanel/blob/1dbac27a0e13cef18501cfa9a9c06382532ac177/src/main.rs) alternately hangs or errors after a dozen or so iterations. If you remove the sleep on line 73, then it works as expected.

The errors seen so far are:
* `ConnectionClosed` on line 53: doesn't prevent progress so is currently ignored;
* `connect: ApplicationClosed(ApplicationClose { error_code: 0, reason: b"" })` on line 154: 2 bytes have been sent on line 148 and `finish` has been called on line 51, so I'd expect lines 154-157 to succeed. May be same as #641, disappears when I remove the error checking here: https://github.com/djc/quinn/blob/7122eab85712b15b598998b324f3e777bed57ae6/quinn/src/connection.rs#L88-L92
* A hang waiting on `SendStream::finish`, with strace showing the process blocked on mio's epoll_wait/kevent call.

These manifest identically for me on Linux and macOS. I hope I'm not doing anything that shouldn't be expected to work, apologies if so.

**Comment by djc** [comment]
I've been staring at this for a bit, but I'm having a hard time understanding what's conceptually going on, what with all the eithering, zipping and such. I think you make pairs of endpoints and then have 2 tasks per pair to cover both directions of communications, and then each of these tasks cycle through either (a) setting up a new connection + stream there is none, (b) randomly ending the stream (and thus ideally also the connection) or (c) sending some data and receiving some data. Does that seem correct?

**Comment by Ralith** [comment]
Thanks for the intensive testing! This sort of thing is a huge help for ferreting out odd corner cases.

> 2 bytes have been sent on line 148 and finish has been called on line 51, so I'd expect lines 154-157 to succeed

I think I know what's going on for this one, and it's an interesting case. The transport layer has received and fully acknowledged the transmitted data, prompting the sender to close the connection, all prior to the receiving application layer (your code) seeing the connection at all. The code you cite in connection.rs is therefore incorrect. #647 fixes it by only returning an error from `Connecting` if the handshake failed, which guarantees that if any data was acknowledged, the application has the opportunity to read it.

**Comment by Ralith** [comment]
> ConnectionClosed on line 53: doesn't prevent progress so is currently ignored;

If the peer closes the connection after reading your finished stream, this is an expected possible outcome. A closed connection will make no further attempts to (re)transmit acknowledgements. That said, I haven't inspected the control flow in your test case closely enough to be sure whether that's what's happening.

I can see how this might be a bit of a footgun for messages that must be delivered reliably but which will prompt a peer to close the connection. One workaround would be to use bidirectional streams and wait the receive half to be finished by the peer (perhaps without sending any data at all) after finishing the send half. If I can't think of anything else after some rest I'll raise the question in the implementers' slack and see how others have handled this.

**Comment by alecmocatta** [comment]
Thanks for the fix in #647!

Here's a simpler test case: https://github.com/alecmocatta/chanel/blob/reduced-hang/src/main.rs

> If the peer closes the connection after reading your finished stream, this is an expected possible outcome.

I follow, though I do find this surprising. If the shutdown is clean, i.e. all bytes written to the SendStream have been read from the RecvStream before it's dropped, then it feels to me the notion of `finish` itself is successful. Any future operations I would expect to error. Having said that I agree with your workarounds, and interpreting the `ConnectionClosed` as acknowledgment is acceptable (though unfortunately does mask the genuine error of the remote end closing the connection early).

**Comment by Ralith** [comment]
> If the shutdown is clean, i.e. all bytes written to the SendStream have been read from the RecvStream before it's dropped, then it feels to me the notion of finish itself is successful.

Unfortunately there's no way for the sender to know this has happened unless it receives an acknowledgement, and if the peer decides to close the connection after reading the data there's no way to guarantee that such an acknowledgement would be delivered.

> though unfortunately does mask the genuine error of the remote end closing the connection early

You can call `Connection::close` explicitly to distinguish error cases from graceful shutdown.

**Comment by alecmocatta** [comment]
> if the peer decides to close the connection after reading the data there's no way to guarantee that such an acknowledgement would be delivered.

I see, thanks for clearing that up.

> You can call `Connection::close` explicitly

Good idea, thank you!

---

The hang in my original post can be avoided by waiting till after `RecvStream::read` has returned `None` before dropping it. Specifically uncommenting line 118 in the simpler test case makes the hang go away. It does however reveal another hang, though I believe it might be a bug in tokio – I will investigate further!

I'm leaving this issue open as I believe `SendStream::finish` hanging in this situation to be a bug but please correct me if I'm wrong.

**Comment by Ralith** [comment]
> The hang in my original post can be avoided by waiting till after RecvStream::read has returned None before dropping it.

Interesting. Perhaps stopped streams aren't properly waking up their writer task. I'll try to confirm/refute tonight.

> It does however reveal another hang, though I believe it might be a bug in tokio – I will investigate further!

Thanks for your ongoing work here!

> I'm leaving this issue open as I believe SendStream::finish hanging in this situation to be a bug but please correct me if I'm wrong.

Based on your descriptions, I agree that the behavior seems suspect. It is only correct for `finish` to hang if the stream is blocked on flow control and the peer never issues any additional credit (i.e. lots of data was written but never read by the receiving application), or if the peer has gone away and the idle timeout was disabled.

**Comment by Ralith** [comment]
Turned out to be a trivial oversight, easily found thanks to the consistent repro; happened on the third iteration every time in release mode!

I think a randomized integration test like this would be a really good thing for us to have in CI, albeit probably not with quite so many iterations by default.
