### ISSUE TITLE
Stream data corruption

### ISSUE THREAD

**Issue by alecmocatta** [djc/quinn#652]
Data sent along a stream sometimes differs from the data received. [Test case here](https://github.com/alecmocatta/chanel/blob/corruption/src/main.rs). It takes a while (ballpark ~30k iterations in my case) to reproduce for me on macOS on localhost with no packet unreliability configured.

Comparing the hex dumps from a few different repros, 1167*n (typically 1 but sometimes 2) bytes seem to be duplicated at the beginning, and that same number deleted at some random other offset.

**Comment by Ralith** [comment]
Thanks for reporting this! This is a serious issue. Either we're generating incorrect stream frames, or we're assembling them incorrectly. My inclination is to suspect the latter, as that logic has changed most recently. Trace logs of an instance would allow us to confirm, and will be sufficient to generate a minimal testcase if it's the assembler.

**Comment by Ralith** [comment]
Are you running in release or debug mode? I ran in release for a good while and wasn't able to reproduce.

**Comment by alecmocatta** [comment]
Release mode. I've included a trace [here](https://github.com/alecmocatta/chanel/blob/ba1219958a013df7f53b330231e024e9a0b203f6/src/corruption.txt).

**Comment by Ralith** [comment]
Thanks! Unfortunately this doesn't include the interesting segment. Could you upload the whole thing, maybe compressed? Setting `BUF` much smaller and/or validating data as it comes in might also help trim things down a bit.

**Comment by alecmocatta** [comment]
Full trace [here](https://github.com/alecmocatta/chanel/blob/00859839fdd02033e9ba3d9a369652911182323f/src/corruption.txt). Took a few runs but got one where it happened soon enough that the trace wasn't 0.5GiB!

**Comment by djc** [comment]
If your reproduction path isn't too onerous, might be interesting to try this against 0.5.0 (and if it works correctly there, bisect?).
