### ISSUE TITLE
RFE: Provide a count of open streams

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#654]
It would be nice to have a count of outbound streams that have not been finished yet.  When this count is zero, the connection can be safely closed.

**Comment by djc** [comment]
We can do that, or maybe we should just provide an `is_idle()` getter instead? This could potentially also be more nuanced about remaining open streams' states.

**Comment by djc** [comment]
We could also consider something similar at the `Endpoint` level, perhaps.

**Comment by Ralith** [comment]
I'm a bit ambivalent about this sort of thing. On the one hand, it's not strictly necessary; an API user can easily maintain such a count themselves. On the other hand, it's easy for us to do too and if we provide it there's less opportunity for error.

> We could also consider something similar at the Endpoint level, perhaps.

Is this covered by `Endpoint::wait_idle`? We already have that one because connections' draining state isn't user-visible, so there's no good way for a user to determine idleness themselves. Might be a good model here too.

The naming gives me pause, also. We (and QUIC implementations in general) use "idle" in "idle timeout" to mean roughly "a period in which no packet was received," which is very different than having no streams open. There will be confusion if we have accessors that indicate that a connection is "not idle" when an idle timeout occurs.

**Comment by DemiMarie-parity** [comment]
> I'm a bit ambivalent about this sort of thing. On the one hand, it's not strictly necessary; an API user can easily maintain such a count themselves. On the other hand, it's easy for us to do too and if we provide it there's less opportunity for error.

Most non-trivial uses that I can think of will need such a count, and maintaining it manually is error-prone.

> > We could also consider something similar at the Endpoint level, perhaps.
> 
> Is this covered by `Endpoint::wait_idle`? We already have that one because connections' draining state isn't user-visible, so there's no good way for a user to determine idleness themselves. Might be a good model here too.

That’s only at the `quinn` level, not the `quinn-proto` level.

> The naming gives me pause, also. We (and QUIC implementations in general) use "idle" in "idle timeout" to mean roughly "a period in which no packet was received," which is very different than having no streams open. There will be confusion if we have accessors that indicate that a connection is "not idle" when an idle timeout occurs.

Agreed.  `Connection::flushed(&self) -> bool` perhaps?

**Comment by Ralith** [comment]
> Most non-trivial uses that I can think of will need such a count

Can you give some examples? Most applications I can think of take the very simple approach of not closing the connection until every task that uses it has completed.

**Comment by djc** [comment]
> The naming gives me pause, also. We (and QUIC implementations in general) use "idle" in "idle timeout" to mean roughly "a period in which no packet was received," which is very different than having no streams open. There will be confusion if we have accessors that indicate that a connection is "not idle" when an idle timeout occurs.

Oh, the name wasn't my core argument. More "providing a count so we can calculate this bit of information" vs "providing the bit of information directly". That said, I don't think `flushed()` is an improvement over `is_idle()`. Maybe flip the meaning and use `is_active()`?

**Comment by Ralith** [comment]
That still seems confusing if you have long-lived streams that might not be constantly in use, or if you're making significant use of non-stream communications like application datagrams. How about `has_open_streams`?

**Comment by djc** [comment]
Works for me.

**Comment by DemiMarie-parity** [comment]
Works for me too.

**Comment by djc** [comment]
@DemiMarie-parity would you have the opportunity to implement this?

**Comment by DemiMarie-parity** [comment]
@djc Yes
