### ISSUE TITLE
H3 tests::incoming_request_stream_ends_on_client_closure hanging under coverage

### ISSUE THREAD

**Issue by djc** [djc/quinn#673]
For example, here: https://github.com/djc/quinn/runs/497269815?check_suite_focus=true

**Comment by djc** [comment]
tests::incoming_request_stream_closed_on_client_drop seems to be similarly intermittent.

**Comment by stammw** [comment]
I think it's caused by the same problem as the one I'm trying to solve on the 0-RTT PR. Seems to me that CONNECTION_CLOSE makes some of the peer's API hang forever under certain conditions.

Maybe we can disable them on coverage or globally ?

**Comment by Ralith** [comment]
Ideally you'd fix the hang (since users will be affected by it as well), but marking known-broken tests as ignored is acceptable in the spirit of keeping other work unobstructed if the issue is subtle.

**Comment by stammw** [comment]
@Ralith Do you think #686 could have an influence on this, by any chance?

I reactivated the faulty tests on master and ran them several times under tarpaulin, which did not reproduce the timeouts.

**Comment by djc** [comment]
Maybe create a PR to reactivate them and rerun the CI jobs a few times (there's a button in the upper right corner of the Actions page)?

**Comment by stammw** [comment]
Done on #687

**Comment by Ralith** [comment]
I haven't investigated the h3 tests, so I could only guess. It's certainly possible, though!

**Comment by djc** [comment]
Let's close this for now, then.
