### ISSUE TITLE
Slow transfer rate

### ISSUE THREAD

**Issue by vjyanand** [djc/quinn#688]
Trying to send a file from client to server using [quinn](https://github.com/djc/quinn) . I see time taken to transfer files is 5x slower than `scp`. Here is code for [Server](https://github.com/vjyanand/quic-send-rust/blob/quinn/src/bin/server.rs) and [Client](https://github.com/vjyanand/quic-send-rust/blob/quinn/src/bin/client.rs). Can you please help me identify issue in using the library. Sorry, if I ask, but I don't understand slowness with the code.

**Comment by Ralith** [comment]
Thanks for the report! I had a look through your code and didn't see any obvious mistakes. Can you provide some details on your test environment? In particular:
- Debug or release build
- Theoretical link capacity on client/server
- Latency and packet loss on the path
- Exact speeds observed for scp and quinn
- Any observed variation in quinn speed over the course of a single large transfer
- What CPU the client/server have
- CPU load on client/server before and during transfer
- client/server OS

Quinn could definitely be faster (see e.g. https://github.com/djc/quinn/issues/501) but we reliably hit >1Gbps on loopback tests, so depending on details it's possible there's something interesting going on here.

**Comment by Ralith** [comment]
Closing as it's been more than two weeks without any response from reporter.
