### ISSUE TITLE
Can't send/receive more than `stream_window_bidi` roundtrip messages without the connection timing out

### ISSUE THREAD

**Issue by SriRamanujam** [djc/quinn#694]
Hi all,

I'm currently trying to write my own QUIC server and client based on quinn v0.6.0, and I can't make more than `stream_window_bidi` roundtrip messages without the connection timing out. I have a minimal reproduction that narrows it down, but I'm unsure what is causing the problem.

Say, for example, that `stream_window_bidi` is set to 10 on the server side. The first 10 bidi streams the client opens on the connection work fine. On the 11th, the client is able to send the data, the server is able to receive the data, but the server hangs trying to write the response to the send stream, and the connection eventually times out. Enabling keepalive just makes the server hang forever. 

I've got a minimal reproduction repo available at https://github.com/SriRamanujam/quinn_minimal_network_repro. `stream_window_bidi` has been set to 10 on the server side. The client simply makes requests in a loop once a second. I've also attached traces for the client and server. 

[client_trace.log](https://github.com/djc/quinn/files/4398109/client_trace.log)
[server_trace.log](https://github.com/djc/quinn/files/4398110/server_trace.log)

/cc @Ralith

**Comment by seamlik** [comment]
Happens to me as well.

**Comment by Ralith** [comment]
Thanks for this excellent bug report! The repro made identifying the root cause easy. I've drafted a fix at https://github.com/djc/quinn/pull/695.
