### ISSUE TITLE
Implement the 'd' QPACK dynamic table H3 test

### ISSUE THREAD

**Issue by stammw** [djc/quinn#702]
> One or both endpoints insert entries into dynamic table and subsequenly reference them from header blocks

This will likely need some `spy` features that the interop client would use to check the state of dynamic table. What do you think of adding a feature flag to achieve this ?

**Comment by djc** [comment]
Yeah, I think a feature flag would make sense for this.

**Comment by Ralith** [comment]
We'll need similar stuff in the lower-level crates too, e.g. for #706 and #707. I'd suggest naming the feature something a little more obvious like `interop_test_accessors`, though.

**Comment by djc** [comment]
Done.
