### ISSUE TITLE
Interop Throughput test `T`

### ISSUE THREAD

**Issue by stammw** [djc/quinn#703]
> Download objects named /5000000 and /10000000 on separate consecutive connections over both H2 and H3 (0.9 if H3 not available). H3 should at most be 10% slower than H2.

Shouldn't be too hard. Here are the alternatives I can think of:
- Use static files with nginx
- write an `h2` implementation that offers exactly the same service
- write an `hyper` implementation

For the last two: should the implementation be a part of the `interop/server` bin ?

**Comment by djc** [comment]
hyper is probably easier for this. Yes, I think it would make sense to make it part of the interop/server, that would make it easy to deploy both at the same time.

**Comment by stammw** [comment]
Closing via #709
