### ISSUE TITLE
Quinn with Framed

### ISSUE THREAD

**Issue by tekjar** [djc/quinn#715]
Hi. I'm trying to use quinn (for the first time) with framed here

https://github.com/tekjar/numbers/blob/master/tcpackserver/quicackserver/src/main.rs

Am I doing anything wrong there?

It fails with this error
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: TimedOut, error: TimedOut }', quicackserver/src/main.rs:72:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: TimedOut, error: TimedOut }', quicackserver/src/main.rs:104:17
```

**Comment by djc** [comment]
It looks like your server is not set up to receive incoming streams. Instead, it's initiating its own streams and sending stuff to the client, which I think is not what you intended. Rather than using the `NewConnection.connection`, you should get the `bi_streams` members and streams out of its `Stream` impl. Let me know if that helps!

**Comment by tekjar** [comment]
@djc Thanks. That work. I'm seeing a throughput of 130 MB/s in my machine with cpu scaling disabled. Tokio tcp server is at 430 MB/s. Is this due tls or are there ways to optimize this?

**Comment by djc** [comment]
QUIC does use TLS unconditionally. You could try to use tokio-rustls to make the comparison between TCP and QUIC more fair.

Also note that we've started doing some macro-benchmarks comparing HTTP/2 (with tokio + rustls + h2 through hyper) and HTTP/3 (quinn-h3) and we're seeing pretty similar performance -- it really depends on your actual workload.

**Comment by Ralith** [comment]
There's also performance work still to be done on quinn, e.g. #501. That said if you're not handling gbps of traffic per core, CPU time isn't expected to be a hard bottleneck.

**Comment by djc** [comment]
Going to close this for now as the immediate issue has been fixed.
