### ISSUE TITLE
H3: Add API to monitor client closing request stream

### ISSUE THREAD

**Issue by djc** [djc/quinn#723]
In h2, `SendResponse` has a `poll_reset()` method. I think we should have something similar:

https://docs.rs/h2/0.2.4/h2/server/struct.SendResponse.html#method.poll_reset

**Comment by stammw** [comment]
I can work on this if you want ?

**Comment by djc** [comment]
Would be great. There are some other things I'm looking into right now.

**Comment by djc** [comment]
That is, I think we should leverage the `http_body` crate's `Body` trait, which already looks quite similar to what we've got going, and use it in our APIs.

**Comment by djc** [comment]
(Potentially we should constrain our `Body` type to implementing that trait and having some minimal constructors, but not much else.)

**Comment by stammw** [comment]
Yeah sure, HttpBody might also be an for future proxy implementation.
