### ISSUE TITLE
H3: Accept HttpBody in Request<T> and Response<T>

### ISSUE THREAD

**Issue by stammw** [djc/quinn#724]
That is, I think we should leverage the `http_body` crate's `Body` trait, which already looks quite similar to what we've got going, and use it in our APIs.

_Originally posted by @djc in https://github.com/djc/quinn/issues/723#issuecomment-616496369_

**Comment by stammw** [comment]
I'm afraid `http_body` is an interface for upon-hyper layers. 

From the `hyper` code, the `h2` glue reads from HttpBody [here](https://github.com/hyperium/hyper/blob/master/src/proto/h2/mod.rs#L159), then writes into a protocol-specific API [here](https://github.com/hyperium/hyper/blob/master/src/proto/h2/mod.rs#L169). It also check a bunch of state,  among which stream reset check.

I guess we'll have to parametize `BodyWriter<B>` with a bound on `bytes::Buf`, and offer some "context + poll" methods to do exactly the same.

The problem with implementing `From<http_body::Body> for Body` is that we'll bypass the `Payload` abstraction [here](https://github.com/hyperium/hyper/blob/master/src/body/payload.rs#L13).

If we want to hold a `http::Body` into a `quinn_h3::Body` variant, we'd have to store it as a `&dyn HttpBody` and it brings other problems with ownership then.

**Comment by djc** [comment]
The `Payload` abstraction is very thin, and I think Sean is okay with removing it. I have a PR to do so: https://github.com/hyperium/hyper/pull/2188

**Comment by djc** [comment]
I was indeed just in the process of writing a `PipeToSendStream` variant for H3.

**Comment by stammw** [comment]
Okay, so why not binding `BodyWriter<T>` to `T: http_body::Body` directly then ?

**Comment by djc** [comment]
I think that's what I was suggesting? 😁

**Comment by stammw** [comment]
Haha, yeah, I understood having a `Body::Stream(http_body::Body)` variant from previous conversations. Makes things easier I guess :)

**Comment by stammw** [comment]
closed via #734
