### ISSUE TITLE
H3: allow cancellation of request after starting response

### ISSUE THREAD

**Issue by djc** [djc/quinn#725]
Since `Sender::send_response()` and `Sender::cancel()` both take `self`, you can't cancel the response after starting to write it.

**Comment by stammw** [comment]
So `SendResponse` will come back as a named future again then.

**Comment by djc** [comment]
In general, hyper internals don't use async but mostly rely on some named futures and lots of `poll_*()` methods. But, I found `AsyncWrite::poll_write_buf()` which is useful here.

**Comment by stammw** [comment]
Good thing we didn't  `Box<dyn Future>` everything.

**Comment by stammw** [comment]
I'll check if that has been solved by #734. Complete tests if it's the case.
