### ISSUE TITLE
H3: "Error: QUIC protocol error: timed out"

### ISSUE THREAD

**Issue by midcontinentcontrols** [djc/quinn#743]
MacOS 10.15.4 Catalina

Attempting to run the H3 example. The server starts fine:
```
~/Repositories/quinn/quinn-h3$ cargo run --example h3_server  
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `/Users/thomashavlik/Repositories/quinn/target/debug/examples/h3_server`
May 03 16:47:42.207  INFO h3_server: server listening on 0.0.0.0:4433
```
Client times out:
```
~/Repositories/quinn/quinn-h3$ cargo run --example h3_client
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `/Users/thomashavlik/Repositories/quinn/target/debug/examples/h3_client`
Error: QUIC protocol error: timed out
```

**Comment by stammw** [comment]
Thanks for the report!

@djc you are able to test on macos IIRC? I'll try to reproduce but if I cannot, could you help on that?

**Comment by Ralith** [comment]
This is very likely a case of `localhost` resolving to an IPv6 address, whereas the `h3_server` example defaults to listening on IPv4. Try `cargo run --example h3_server -- --listen '[::]:4433'` instead.
