### ISSUE TITLE
authentication_data is unreliable during handshake

### ISSUE THREAD

**Issue by Ralith** [djc/quinn#749]
When the TLS `ClientHello` is not fully contained within the first packet we receive (e.g. due to reordering or large size), the application may be notified of an incoming connection for which `authentication_data` returns nothing.  Processing 0-RTT with minimum latency requires access to ALPN results, so waiting for the handshake to complete is not an acceptable solution. quinn-proto should therefore expose an event notifying the application of when `authentication_data` has become populated, and quinn should expose that information through a future.

**Comment by Ralith** [comment]
Per [the TLS 1.3 RFC](https://tools.ietf.org/html/rfc8446#section-2), ALPN may be available well before client certificates, so there's no point at which all of what we currently term "authentication data" becomes available simultaneously. It's probably sufficient to have a mid-handshake point and a "connection fully established" point, so still only one new event needed, but we may want to reconsider bundling all authentication data into a single strict.

**Comment by djc** [comment]
So the reason this is important is mainly/just that we want to do processing as soon as the ALPN is available, right? Rather than wait with this processing until the handshake is complete (at which point we'll know for sure if we got an ALPN or not)?

If so, maybe we could get rustls to return some status enum from `Session::process_new_packets()`, some variants of which we could then translate to application events?

**Comment by Ralith** [comment]
> So the reason this is important is mainly/just that we want to do processing as soon as the ALPN is available, right?

Right, because for minimum latency we want to be able to send a 0.5-RTT response to 0-RTT data, and if a server supports multiple protocols (e.g. the interop server) then we can't process the 0-RTT data without ALPN. I suppose we could wait until the first 0-RTT data is read before inspecting ALPN but that's very inconvenient for the application, compared to passing off the entire `Connection` to protocol-specific logic.

> If so, maybe we could get rustls to return some status enum from Session::process_new_packets(), some variants of which we could then translate to application events?

I think polling the rustls session's status after we pass it `CRYPTO` data, as we already do to check for handshake completion, works just fine, and doesn't require upstream changes.
