### ISSUE TITLE
Internal unsoundness in cmsg code

### ISSUE THREAD

**Issue by DemiMarie-parity** [djc/quinn#763]
The cmsg code is internally unsound, since CMSG_\* assume (without checking) that the buffers they operate on are well-formed.  This code is not part of the public API, and is only called on buffers filled by the kernel.  Since the kernel only fills valid buffers, this is safe.

**Comment by Ralith** [comment]
Can you be more specific? Those calls are all wrapped behind unsafe interfaces that document their requirements.

**Comment by DemiMarie-parity** [comment]
The documentation doesn’t mention the requirement that the buffer be well-formed.

**Comment by Ralith** [comment]
What documentation? What well-formedness property?

**Comment by DemiMarie-parity** [comment]
`libc::CMSG_*` do not check that `cmsghdr.cmsg_len` is in bounds.  If it isn’t, attempting to use the cmsghdr will access junk memory.

**Comment by Ralith** [comment]
Okay, thanks. In the future, a PR would probably be more efficient.
