### ISSUE TITLE
H3: make WriteFrame take a mutable reference of SendStream

### ISSUE THREAD

**Issue by stammw** [djc/quinn#768]
Writing some tests and test helpers, I figured out owning `SendStream` into `WriteFrame` brings pain when using it. 

In my mind, this technique belongs more to pre-std-futures era. What do you think about this?

In the end, only `SendData` should own it, and pass it through a pin projection to the underlying layers.

**Comment by Ralith** [comment]
I'm not familiar with the h3 API here, but in general borrowing is much more ergonomic if you want to do anything with the object in question afterwards, or operate on objects stored in places that aren't trivially destructured (which is why even `SendStream::finish` borrows).

**Comment by djc** [comment]
A potentially related issue: I saw some structures that both held a `SendStream` (which internally holds a `ConnectionRef`) and a separate `ConnectionRef`. This seems like a bit of a code smell and should maybe be refactored if possible (or commented). I also worry it might lead to issues with refcounts being weird.

**Comment by djc** [comment]
(Looking at the code a little bit, it does indeed look like `WriteFrame` should not own the `SendStream`. Let me know if you need help with the pin projections -- it can be a bit fiddly, in my experience.)

**Comment by stammw** [comment]
Good catch for the `ConnectionRef` duplication. I imagine you are speaking about `SendHeaders` and associated. These could be removed once `WriteFrame` no longer take ownership of `SendStream`, or turned into `SendData` methods.

I guess `HttpBody` refactoring started a change of which this issue matters are part of, and that will benefit the codebase a lot.

If you want to work on this, go ahead. I'll find other opportunities to learn pin projection usage. Plus I'm kind of slow on my current PRs.

**Comment by djc** [comment]
In the end it didn't make sense for `WriteFrame` to hold its own reference to the `SendStream`, since it's always a part of the `SendData` that owns the `SendStream`. Fixed stuff up by replacing the `Future` impl for `WriteFrame` with a simple `poll_send()` method that takes the `&mut SendStream` explicitly.
