### ISSUE TITLE
Improve API/documentation for TLS client authentication

### ISSUE THREAD

**Issue by Voker57** [djc/quinn#772]
From what I can see, quinn offers no way for client to supply a certificate and a server to verify it, and such a feature is often required.

**Comment by djc** [comment]
I'm quite sure that you can in fact do this, but looking at our documentation I can see that it is pretty hard to find out conclusively how you would do this. Can you tell me where you looked and how you concluded that it's impossible? This might help us find the right places to improve.

[`ClientConfig`](https://docs.rs/quinn/0.6.1/quinn/generic/struct.ClientConfig.html) has a public `crypto` field that holds a `ClientConfig` type which is an associated type of the `crypto::Session` trait impl. Our default impl is based on rustls, so you should be able to set the `ClientConfig` (probably using [`EndpointConfigBuilder::default_client_config()`](https://docs.rs/quinn/0.6.1/quinn/generic/struct.EndpointBuilder.html#method.default_client_config) to a `rustls::ClientConfig` that is [wired up correctly](https://docs.rs/rustls/0.17.0/rustls/struct.ClientConfig.html#method.set_single_client_cert).

Wow, that really is very hard to grok from the docs. I'll see if we can come up with ways to improve on that (and maybe write an example that does this).

**Comment by Voker57** [comment]
I was looking at https://docs.rs/quinn/0.6.1/quinn/generic/struct.ClientConfigBuilder.html and saw no option for that.

Yeah, looks like it should in fact be possible, thanks for explanation. As for documentation. adding crypto to Builder and possibly adding an example with client certificates would be nice!

**Comment by Ralith** [comment]
Good ideas; thanks for bringing this to our attention!

**Comment by DemiMarie-parity** [comment]
https://github.com/libp2p/rust-libp2p/pull/1334 shows one way to use client certificates.

**Comment by djc** [comment]
Have a look at #784 for some documentation improvements. Would this have helped?

**Comment by Voker57** [comment]
Yeah, LGTM.
