### ISSUE TITLE
Flow control error encountered when program is under heavy mixed load

### ISSUE THREAD

**Issue by SriRamanujam** [djc/quinn#774]
I'm going to be honest, the title is probably not 100% accurate as I'm not entirely sure yet what's going on. This could be a Tokio or a Quinn bug. All I can say for sure is that I have developed a reproducer that makes it happen _some_ of the time. 

[The reproducer is here](https://github.com/SriRamanujam/quinn_minimal_network_repro/tree/transport_error). 

My exact steps to run the reproducer are:

```sh
$ cargo build --release
$ RUST_LOG=quinn=trace target/release/server
(in another terminal) 
$ RUST_LOG=quinn=trace target/release/client
```

Most of the time, the client and server negotiate flow control properly and back off. If that happens, ctrl-c both processes and try again. Eventually you will hit a run where the flow control error happens. In my local testing, if the error happened, it always happened within a minute or two. 

I've also attached trace logs for server and client from a failed run, in case it helps.
[client_log.txt](https://github.com/djc/quinn/files/4630254/client_log.txt)
[server_log.txt](https://github.com/djc/quinn/files/4630257/server_log.txt)

**Comment by Ralith** [comment]
Flow control errors are always a QUIC implementation bug; no tokio malfunction (short of astronomically unlikely coincidence of undefined behavior) can produce them.

The supplied code does successfully reproduce the issue for me, thanks! This will be a huge help in identifying the error and validating a fix.

**Comment by Ralith** [comment]
This test case revealed a number of issues, which I believe I've addressed in https://github.com/djc/quinn/pull/776. Want to give it a try?

**Comment by SriRamanujam** [comment]
This seems to resolve the issue I was encountering. Thank you for the fix!

**Comment by Ralith** [comment]
Awesome!
