### ISSUE TITLE
Wireshark SSLKEYLOGFILE decryption failed  

### ISSUE THREAD

**Issue by SSebo** [djc/quinn#835]
I'm new to quinn. Maybe it is a wireshark bug?

- When `enable_keylog` and set `SSLKEYLOGFILE=/tmp/keylog.file` env, `keylog.file` generates ok.
- When set wireshark preferences `TLS -> (Pre)-Master-Secret log filename` to `keylog.file`, 
wireshark shows `[Failed to create decryption context: Decryption (checktag) failed: Checksum error]`

BTW, Is there any other way to debug quinn ?

**Comment by djc** [comment]
What version of Wireshark are you using? Only the latest pre-release snapshots typically have support for the latest QUIC draft. You can see more information here: https://github.com/quicwg/base-drafts/wiki/Tools#wireshark

**Comment by SSebo** [comment]
Wireshark Version 3.2.5 (Git commit ed20ddea8138) 
Quinn use the latest master commit
Thanks a lot. I'll have a try.
