### ISSUE TITLE
request: function on Endpoint to send raw UDP datagram (for NAT holepunching)

### ISSUE THREAD

**Issue by kwantam** [djc/quinn#836]
I have been thinking about using quinn in an application that wants to do NAT traversal via [UDP hole-punching](https://tools.ietf.org/html/rfc5128#section-3.3). QUIC is in some ways an ideal protocol for this, since all traffic related to a given QUIC endpoint is on the same port number.

In some cases, holepunching requires sending small number of extra UDP packets (see [this description](https://tools.ietf.org/html/rfc5128#section-3.3.1) for a step-by-step description). It would be super cool if quinn Endpoints had explicit support for this---say, a function that accepts a SocketAddr and a Bytes and sends a packet from the Endpoint's UDPSocket to the specified address, with the specified payload.

I should note that in principle it's possible to holepunch using the current API, simply by attempting to start connections from both hosts. The major downside is that this will end up establishing two different connections, and therefore will result in the execution of two separate TLS handshakes. This seems pretty wasteful.

Does this seem like a feature that y'all would consider adding? I would be happy to work up a PR for it. Also happy to discuss further.

(BTW, I haven't forgotten about #834; I hope to have a PR for that soon, but other things got in the way.)

Thanks!

**Comment by Ralith** [comment]
Graceful support for UDP hole punching sounds like a great thing to have. Could this be addressed with `SO_REUSEADDR` or similar?

**Comment by kwantam** [comment]
Great point!

I think `SO_REUSEADDR` does not quite work, at least on Linux. Per [socket(7)](https://www.man7.org/linux/man-pages/man7/socket.7.html),

> Indicates that the rules used in validating addresses supplied in a bind(2) call should allow reuse of local addresses.  For AF_INET sockets this means that a socket may bind, except when there is an active listening socket bound to the address.

`SO_REUSEPORT` could work:

> Permits multiple AF_INET or AF_INET6 sockets to be bound to an identical socket address.  This option must be set on each socket (including the first socket) prior to calling bind(2) on the socket.

On the other hand, since `SO_REUSEPORT` is not portable, it appears to be unsupported by UDPSocket. I'm not sure of your thoughts on platform-specific code, but it seems like adding functionality to Endpoint would sidestep this issue.

(That said, I'm targeting Linux, so probably `SO_REUSEPORT` would work. And probably that would mean no need to change anything about quinn, since `Endpoint::rebind` would let me set `SO_REUSEPORT` on the Endpoint's socket...)

**Comment by Ralith** [comment]
The tricky question is whether it could be made to not interfere with unrelated incoming QUIC packets. On consideration, I think there's a safer and more portable solution: use [`UdpSocket::try_clone`](https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.try_clone) to obtain a duplicate copy of the socket, and send data on that directly. Do I understand correctly that there's no need to receive?

**Comment by kwantam** [comment]
Yes, there should be no need for either end to receive one of these datagrams. They're just there to make the NAT happy.

**Comment by Ralith** [comment]
To be clear, this is something you can already do. Construct your socket manually, clone it, then pass one of the clones into [`EndpointBuilder::with_socket`](https://docs.rs/quinn/0.6.1/quinn/generic/struct.EndpointBuilder.html#method.with_socket), keeping the other around for hole-punching use as needed--assuming the hole punching needs to overlap with the endpoint's lifetime at all.

**Comment by kwantam** [comment]
Yup, this makes sense. Seems like a pretty clean solution. :+1:
