### ISSUE TITLE
Tracking issue for "reached the type-length limit" in interop crate

### ISSUE THREAD

**Issue by djc** [djc/quinn#839]
This seems to be an instance of https://github.com/rust-lang/rust/issues/54540 which apparently has gotten worse due to https://github.com/rust-lang/rust/pull/75443 (which has been on nightly since 2020-08-14 and is now also a part of 1.46.0-beta.5. There seems to be an interaction with tracing, described in https://github.com/tokio-rs/tracing/issues/616.

First noticed in CI, for example https://github.com/djc/quinn/pull/837/checks?check_run_id=1017422950.

**Comment by Ralith** [comment]
The error appears to reference this code:

```rust
    let results = future::join_all(peers.into_iter().map(|peer| async move {
        let span = info_span!("peer", name = peer.name.as_str());
        let result = run(&peer, keylog).instrument(span).await;
        (peer, result)
    }));
```

Maybe `info_span!` is expanding to something wildly complex? Can't otherwise see how this would have anything to do with tracing (or indeed be an issue at all).

**Comment by tmandry** [comment]
cc https://github.com/rust-lang/rust/issues/64496

**Comment by djc** [comment]
Fixed (well, worked around) in https://github.com/djc/quinn/pull/844.
