### ISSUE TITLE
impl Debug for TlsSession

### ISSUE THREAD

**Issue by imp** [djc/quinn#841]
Please derive (or implement) `Debug` for `crypto::rustls::TlsSession`. `TlsSession` is default session type parameter for many other structs, and their `derive(Debug)` doesn't work while `TlsSession` is missing `Debug` impl.

**Comment by djc** [comment]
What "many other structs" do you want to have `Debug` impls on?

**Comment by imp** [comment]
Well, here is the partial list:

1. `ClientConfig`
2. `Connecting`
3. `Connection`
4. `Datagarms`
5. `Endpoint`
6. `EndpointBuilder`
7. `Incoming`
8. `NewConnection`
9. `RecvStream`
10. `SendStream`

**Comment by imp** [comment]
It looks like simply deriving `Debug` on `TlsSession` and `SessionKind` does the trick. Is that ok with you?
