### ISSUE TITLE
Usage of read and read_exact

### ISSUE THREAD

**Issue by lionel1704** [djc/quinn#842]
I'm trying to use the `read()` and `read_exact()` to read bytes from an incoming stream. However they don't seem to be working as expected.
I've put together a small example [here](https://github.com/lionel1704/quinn-demo/blob/master/src/lib.rs).

The point of focus would be:
```
        // Data is always empty and len is None
        
        let mut data = Vec::new();
        let len = recv_b.read(&mut data).await.unwrap();
        println!("Read {:?}, Len {:?}", data, len);
        
        // Data is always empty
        
        let mut data = Vec::new();
        recv_b.read_exact(&mut data).await.unwrap();
        println!("Read: {:?}", data);
        
        // This works
        
        let data = recv_b.read_to_end(100).await.unwrap();
        println!("Read: {:?}", data);
```

Am I missing something? Or should these API be used differently?
Any help would be much appreciated :)

**Comment by djc** [comment]
Would have been helpful if you had stated what you expected to happen versus what you saw happening with your code. However, I think what's happening here is that both `read()` and `read_exact()` can only return the amount of data allocated for the slice you pass in. In your code sample, you pass in empty slices, so you'll never be able to receive any data.

**Comment by lionel1704** [comment]
Thanks for the response @djc 
I expected `read()` to read data from the stream. I imagined I would call `read()` in a loop until it returns `Ok(None)` which indicates that the stream is finished (from the documentation).

And `read_exact()` would read a fixed number of bytes. I wondered why there wasn't a `usize` parameter to that function. The slice size makes sense.

I changed the test to:
```
        // Data is always empty and len is None
        
        let mut data = Vec::with_capacity(100);
        let len = recv_b.read(&mut data).await.unwrap();
        println!("Read {:?}, Len {:?}", data, len);
        
        // Data is always empty
        
        let mut data = Vec::with_capacity(4);
        recv_b.read_exact(&mut data).await.unwrap();
        println!("Read: {:?}", data);
```
But unfortunately, the functions didn't read anything from the stream.
I later tried:
```
        // This works now
        let mut data = [0;32];
        let len = recv_b.read(&mut data).await.unwrap();
        println!("Read {:?}, Len {:?}", data, len);
        
        // This works too
        let mut data = [0; 4];
        recv_b.read_exact(&mut data).await.unwrap();
        println!("Read: {:?}", data);
```
And both of them work as expected :tada: 
I'm happy to close this issue, but, do you think it's possible to allow these functions to work with vectors as well?

**Comment by djc** [comment]
They work with vectors, but your vecs are still length zero; you allocated backing data, but slices need to be fully initialized.

**Comment by Ralith** [comment]
Note that this is the same way that `std::io::Read` works.
