### ISSUE TITLE
transport error "RETIRE_CONNECTION_ID for unissued sequence number" on android

### ISSUE THREAD

**Issue by SSebo** [djc/quinn#845]
- client side full error message: "Custom { kind: Other, error: TransportError(Error { code: PROTOCOL_VIOLATION, frame: None, reason: "RETIRE_CONNECTION_ID for unissued sequence number" }) }"
- server side full error message: "ConnectionClosed(ConnectionClose { error_code: PROTOCOL_VIOLATION, frame_type: None, reason: b"RETIRE_CONNECTION_ID for unissued sequence number" })
Custom { kind: ConnectionAborted, error: ConnectionClosed(ConnectionClose { error_code: PROTOCOL_VIOLATION, frame_type: None, reason: b"RETIRE_CONNECTION_ID for unissued sequence number" }) }
"
- same code on linux and x86 android simulator works very well, only android phone will report this error message

**Comment by SSebo** [comment]
I change keep_alive_interval from 15 to 3, and it works, 
`transport_config.keep_alive_interval(Some(Duration::from_secs(3)));`

**Comment by Ralith** [comment]
Hi, thanks for opening this issue! Even if changing the keep alive interval suppressed the error, this sounds like a bug. What version of quinn are you using? Any chance you could share trace-level logs of it happening?

**Comment by SSebo** [comment]
@Ralith 
- I used a specified commit babb07b079e7e3ac4 which add `quinnCertificate::from_pem` function
- when I set `keep_alive_interval` for both client and server, everything works fine.

**Comment by Ralith** [comment]
Keep-alives should only need to be sent by one side. Is there any chance you could produce trace-level logs? You can get them on stdout by invoking e.g.:

```rust
tracing_subscriber::fmt().with_env_filter("quinn=trace").init()
```

**Comment by SSebo** [comment]
@Ralith I think it is something wrong with my code,  I removed client side `keep_alive_interval`, and everything works well. Some bugs are fixed during these days and I can not produce that error message. 

Thanks a lot!
