### ISSUE TITLE
failed to set up UDP socket: Invalid argument (os error 22) on iOS

### ISSUE THREAD

**Issue by SSebo** [djc/quinn#848]
- Linux, Android, macOS works fine, just iOS failed on both simulator and real phone.
- I changed some code for debugging, found out the error message comes from here. 
https://github.com/djc/quinn/blob/6018f200555c38d178c08b890342fe7d8d4334d7/quinn/src/builders.rs#L62

- I found this code only checks macos
https://github.com/djc/quinn/blob/6ac08773a697596070473344ebf7185503089f65/quinn/src/platform/unix.rs#L41

- Maybe something wrong with  `tokio` or `mio` ?

**Comment by djc** [comment]
Can you try to extend the platform check for `target_os = "macos"` with `target_os = "ios"`? That seems likely to improve things.

**Comment by SSebo** [comment]
@djc Of course. It works well after I modified the platform check as your guide.

**Comment by djc** [comment]
@SSebo it looks like the `only_v6()` API has been removed from mio 0.7 (which tokio 0.3 depends on). It is what we were using previously to detect dual-stack sockets. I wonder, when you were testing this, was that on iOS 14? Would you mind checking again with a recent version? I was just talking to an Apple engineer who says this should have been fixed around the time of macOS 10.15.1 beta 1 (19B68f), meaning that iOS 13 should also have picked up the fix. If it still an issue, maybe you can report it on http://feedbackassistant.apple.com/ (and I can send the issue back to the Apple folks).
