### ISSUE TITLE
Audit uses of `FnvHashMap` for collision attack potential

### ISSUE THREAD

**Issue by djc** [djc/quinn#88]
We currently use `FnvHashMap` in a number of places, presumably because it is faster than the std `HashMap`. However, the reason `FnvHashMap` is not the default, as I understand it, is because it is possible for attackers to generate input data that will cause denial of service through worst-case performance of hash map algorithms.

In `Endpoint`, we currently use `FnvHashMap` for (1) `connection_ids_initial`, (2) `connection_ids`, and (3) `connection_remotes`. (1) seems definitely vulnerable to this style of attack for server endpoints, since clients can randomly pick initial CIDs for their packets, thus triggering collisions. (2) seems safe, since local CIDs are generated by our own code. For (3), I'm not sure how easy it is to spoof IP addresses these days.

**Comment by djc** [comment]
(One might also consider that using `FnvHashMap`s here is a form of premature optimization and we should just switch to std `HashMap`s until benchmarking proves that these matter; in which case we also might want to consider https://github.com/Amanieu/hashbrown.)

**Comment by Ralith** [comment]
> I'm not sure how easy it is to spoof IP addresses these days.

In IPv6, any attacker can easily control at least 80 bits of their IP address in addition to their source port, leaving 48 fixed. No idea if this is enough to be an issue. for hash collisions.

**Comment by Silvea12** [comment]
> (One might also consider that using `FnvHashMap`s here is a form of premature optimization and we should just switch to std `HashMap`s until benchmarking proves that these matter; in which case we also might want to consider https://github.com/Amanieu/hashbrown.)

However, FxHash (what hashbrown uses) is not nessecarily more secure than FnvHash. They explicitly state it's not good to be used where DDoS is a concern - see the disclamer on the readme for https://github.com/cbreeden/fxhash

**Comment by djc** [comment]
As I understand it hashbrown (like the std hash map) can use different hashing algorithms, so we could pick one that's collision-resistant.
